import { useEffect, useMemo, useState } from "react";
import type { TabRendererProps } from "./core";
import { apiGet, apiPost } from "../lib/authApi";

type Analytics = { days:number; daily:{day:string;plays:number;listeners:number}[]; totals:{plays:number;listeners:number;synthetic_plays:number}; countries:{name:string;value:number}[]; genders:{name:string;value:number}[] };

export default function AnalyticsPane(_props: TabRendererProps) {
	const [data,setData]=useState<Analytics|null>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(""); const [preset,setPreset]=useState("steady"); const [total,setTotal]=useState(2500);
	const load=()=>apiGet<Analytics>("/api/analytics/creator?days=30").then(setData);
	useEffect(()=>{void load().catch(()=>{});},[]);
	const max=useMemo(()=>Math.max(1,...(data?.daily||[]).map(x=>x.plays)),[data]);
	const points=useMemo(()=>{const rows=data?.daily||[]; if(rows.length<2)return ""; return rows.map((r,i)=>`${(i/(rows.length-1))*100},${100-(r.plays/max)*92}`).join(" ")},[data,max]);
	const seed=async()=>{setBusy(true);setMsg("");try{const r=await apiPost<{created:number}>("/api/analytics/dev/seed",{days:30,total,preset});setMsg(`Added ${r.created.toLocaleString()} synthetic streams.`);await load();}catch(e:any){setMsg(e?.message==="publish_track_first"?"Publish at least one World track before seeding analytics.":e?.message||"Seed failed.");}finally{setBusy(false)}};
	const reset=async()=>{setBusy(true);setMsg("");try{const r=await apiPost<{deleted:number}>("/api/analytics/dev/reset",{});setMsg(`Removed ${r.deleted.toLocaleString()} synthetic events.`);await load();}catch(e:any){setMsg(e?.message||"Reset failed.");}finally{setBusy(false)}};
	return <div className="h-full overflow-y-auto bg-neutral-950 text-white"><div className="max-w-7xl mx-auto p-5 lg:p-8 space-y-6">
		<div><div className="text-xs uppercase tracking-[.22em] text-cyan-300">Creator intelligence</div><h1 className="text-3xl font-semibold mt-1">Analytics</h1><p className="text-sm text-neutral-400 mt-2">YSong World listener performance. Synthetic development streams are segregated and never need to touch public counts, royalties, rankings or payouts.</p></div>
		<div className="grid sm:grid-cols-3 gap-3"><Card label="Streams" value={data?.totals?.plays||0}/><Card label="Known unique listeners" value={data?.totals?.listeners||0}/><Card label="Synthetic test streams" value={data?.totals?.synthetic_plays||0}/></div>
		<section className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center justify-between gap-3 mb-4"><div><h2 className="font-semibold">Streams · last 30 days</h2><div className="text-xs text-neutral-500">Real and test events shown in this private creator view.</div></div></div><div className="h-60 rounded-xl border border-white/5 bg-black/20 p-3"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="w-full h-full overflow-visible"><line x1="0" y1="100" x2="100" y2="100" stroke="currentColor" opacity=".15" vectorEffect="non-scaling-stroke"/>{points&&<polyline points={points} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke" className="text-cyan-300"/>}</svg></div><div className="flex justify-between text-[10px] text-neutral-500 mt-2"><span>{data?.daily?.[0]?.day||""}</span><span>{data?.daily?.at(-1)?.day||""}</span></div></section>
		<div className="grid lg:grid-cols-2 gap-5"><Breakdown title="Top countries" rows={data?.countries||[]}/><Breakdown title="Gender" rows={data?.genders||[]}/></div>
		<section className="rounded-2xl border border-amber-400/20 bg-amber-400/[.06] p-4"><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><h2 className="font-semibold">Analytics Test Lab</h2><div className="text-xs text-neutral-400 mt-1">Local/dev-only synthetic data generator.</div></div><label className="text-xs">Pattern<select value={preset} onChange={e=>setPreset(e.target.value)} className="block mt-1 rounded-lg bg-neutral-900 border border-white/10 px-3 py-2"><option value="steady">Steady</option><option value="viral">Viral spike</option><option value="release">Release-day surge</option><option value="slowburn">Slow burn</option></select></label><label className="text-xs">Streams<input type="number" min={1} max={50000} value={total} onChange={e=>setTotal(Math.max(1,Math.min(50000,Number(e.target.value)||1)))} className="block mt-1 w-32 rounded-lg bg-neutral-900 border border-white/10 px-3 py-2"/></label><button disabled={busy} onClick={()=>void seed()} className="rounded-xl border border-cyan-400/30 bg-cyan-500/10 px-4 py-2 disabled:opacity-40">Generate test data</button><button disabled={busy} onClick={()=>void reset()} className="rounded-xl border border-red-400/30 px-4 py-2 text-red-200 disabled:opacity-40">Reset test analytics</button></div>{msg&&<div className="text-xs mt-3 text-amber-100">{msg}</div>}</section>
	</div></div>;
}
function Card({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="text-xs uppercase tracking-widest text-neutral-500">{label}</div><div className="text-3xl font-semibold mt-2">{Number(value||0).toLocaleString()}</div></div>}
function Breakdown({title,rows}:{title:string;rows:{name:string;value:number}[]}){const max=Math.max(1,...rows.map(r=>Number(r.value)));return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><h2 className="font-semibold mb-3">{title}</h2><div className="space-y-2">{rows.length?rows.map(r=><div key={r.name}><div className="flex justify-between text-xs"><span>{String(r.name).replaceAll("_"," ")}</span><span>{Number(r.value).toLocaleString()}</span></div><div className="h-1.5 bg-white/5 rounded-full mt-1 overflow-hidden"><div className="h-full bg-white/30 rounded-full" style={{width:`${Math.max(3,(Number(r.value)/max)*100)}%`}}/></div></div>):<div className="text-xs text-neutral-500">No listener data yet.</div>}</div></section>}
