import { useEffect, useMemo, useState } from "react";
import type { AudioIntelligenceReport } from "../audiointelligence/api";
import { curatorApi, type CuratorChannel, type CuratorProfile, type CuratorRecommendation, type CuratorRelease, type CuratorStats, type CuratorSubmission, type Wallet } from "./api";

type Props={onBack:()=>void;initialIntelligence?:AudioIntelligenceReport|null};
type View="match"|"submissions"|"curator";
const panel="rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white/70 dark:bg-neutral-900/45 p-5";
const input="w-full rounded-xl border border-neutral-300 dark:border-neutral-700 bg-transparent px-3 py-2.5 text-sm text-neutral-900 dark:text-neutral-100";
const btn="rounded-xl border border-neutral-300 dark:border-neutral-700 px-3 py-2 text-sm hover:border-violet-500/50 disabled:opacity-40";
const primary="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40";
const pct=(v:number)=>`${Math.round((Number(v)||0)*100)}%`;
const typeLabel=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
function tags(s:string){return [...new Set(s.split(/[,\n]/).map(x=>x.trim()).filter(Boolean))];}

function record(value: unknown): Record<string, unknown>{return typeof value==="object"&&value!==null?value as Record<string,unknown>:{};}
function submissionArtist(s:CuratorSubmission){const release=record(record(s.releaseSnapshot).release);return String(release.artistName||"Artist");}
function submissionTitle(s:CuratorSubmission){const snap=record(s.releaseSnapshot);const track=record(snap.track);const release=record(snap.release);return String(track.title||release.title||"Release");}
function submissionMatchScore(s:CuratorSubmission){return Number(record(s.matchSnapshot).score||0);}

export default function CuratorMarketplaceApp({onBack,initialIntelligence=null}:Props){
  const [view,setView]=useState<View>("match"); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const [wallet,setWallet]=useState<Wallet|null>(null); const [releases,setReleases]=useState<CuratorRelease[]>([]); const [releaseId,setReleaseId]=useState(""); const [trackId,setTrackId]=useState("");
  const [recs,setRecs]=useState<CuratorRecommendation[]>([]); const [subs,setSubs]=useState<CuratorSubmission[]>([]); const [pitches,setPitches]=useState<Record<string,string>>({});
  const [profile,setProfile]=useState<CuratorProfile|null>(null); const [channels,setChannels]=useState<CuratorChannel[]>([]); const [stats,setStats]=useState<CuratorStats|null>(null); const [desk,setDesk]=useState<CuratorSubmission[]>([]);
  const [profileForm,setProfileForm]=useState({displayName:"",organization:"",curatorType:"playlist",bio:"",websiteUrl:"",status:"draft",editorialIndependenceAck:false});
  const [channelForm,setChannelForm]=useState({name:"",platform:"Spotify playlist",url:"",description:"",genres:"",moods:"",sonicTags:"",languages:"en",countries:"",minBpm:"",maxBpm:"",acceptsExplicit:true,submissionCostCredits:"1",responseDays:"7",audienceSize:"0"});
  const selectedRelease=useMemo(()=>releases.find(r=>r.id===releaseId)||null,[releases,releaseId]);

  async function load(){
    try{const [w,r,p,s,d]=await Promise.all([curatorApi.wallet(),curatorApi.releases(),curatorApi.profile(),curatorApi.submissions(),curatorApi.desk()]);setWallet(w.wallet);setReleases(r.releases);setProfile(p.profile);setChannels(p.channels);setStats(p.stats);setSubs(s.submissions);setDesk(d.submissions);if(!releaseId&&r.releases[0]){setReleaseId(r.releases[0].id);setTrackId(r.releases[0].tracks[0]?.id||"");}if(p.profile)setProfileForm({displayName:p.profile.displayName,organization:p.profile.organization,curatorType:p.profile.curatorType,bio:p.profile.bio,websiteUrl:p.profile.websiteUrl,status:p.profile.status,editorialIndependenceAck:p.profile.editorialIndependenceAck});}catch(e){setMessage(e instanceof Error?e.message:"Curator Marketplace could not load.");}
  }
  // Initial fetch only; later mutations call load() explicitly.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(selectedRelease&&!selectedRelease.tracks.some(t=>t.id===trackId))setTrackId(selectedRelease.tracks[0]?.id||"");},[selectedRelease,trackId]);

  async function buildMatches(){if(!releaseId)return;setBusy(true);setMessage("");try{await curatorApi.matchContext({releaseId,trackId:trackId||null,audioIntelligence:initialIntelligence,refreshSeo:true});const r=await curatorApi.recommendations(releaseId,trackId||null,60);setRecs(r.recommendations);setMessage(r.recommendations.length?`Found ${r.recommendations.length} editorial matches.`:"No active matching curators yet.");}catch(e){setMessage(e instanceof Error?e.message:"Matching failed.");}finally{setBusy(false);}}
  async function submit(rec:CuratorRecommendation){if(!releaseId)return;setBusy(true);try{const pitch=pitches[rec.channel.id]||"";await curatorApi.submit({channelId:rec.channel.id,releaseId,trackId:trackId||null,pitch});setMessage(`Submitted to ${rec.channel.name}. Credits purchase review consideration only, never placement.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Submission failed.");}finally{setBusy(false);}}
  async function saveProfile(){setBusy(true);try{await curatorApi.saveProfile(profileForm);setMessage("Curator profile saved.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Profile save failed.");}finally{setBusy(false);}}
  async function addChannel(){setBusy(true);try{await curatorApi.createChannel({name:channelForm.name,platform:channelForm.platform,url:channelForm.url,description:channelForm.description,genres:tags(channelForm.genres),moods:tags(channelForm.moods),sonicTags:tags(channelForm.sonicTags),languages:tags(channelForm.languages),countries:tags(channelForm.countries),minBpm:channelForm.minBpm?Number(channelForm.minBpm):null,maxBpm:channelForm.maxBpm?Number(channelForm.maxBpm):null,acceptsExplicit:channelForm.acceptsExplicit,submissionCostCredits:Number(channelForm.submissionCostCredits)||0,responseDays:Number(channelForm.responseDays)||7,audienceSize:Number(channelForm.audienceSize)||0,active:true});setMessage("Curator channel created.");setChannelForm(v=>({...v,name:"",url:"",description:""}));await load();}catch(e){setMessage(e instanceof Error?e.message:"Channel creation failed.");}finally{setBusy(false);}}
  async function respond(id:string,decision:"accepted"|"rejected"){const summary=window.prompt(decision==="accepted"?"Optional feedback for the artist":"Feedback / reason for rejection")||"";setBusy(true);try{await curatorApi.respond(id,{decision,summary,reasonCode:decision==="accepted"?"editorial_fit":"not_a_fit"});setMessage(`Submission ${decision}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Response failed.");}finally{setBusy(false);}}
  async function markPlacement(s:CuratorSubmission){const url=window.prompt("Published placement URL")||"";if(!url)return;setBusy(true);try{await curatorApi.placement(s.id,{status:"published",url});setMessage("Placement marked published.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Placement update failed.");}finally{setBusy(false);}}

  return <div className="h-full min-h-0 overflow-y-auto bg-neutral-50 dark:bg-neutral-950 text-neutral-900 dark:text-neutral-100"><div className="mx-auto max-w-7xl px-5 py-7 md:px-8 md:py-9">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><button onClick={onBack} className="text-xs text-violet-500">← Tools</button><div className="mt-4 text-[11px] uppercase tracking-[.24em] text-violet-500">Phase 24</div><h1 className="mt-1 !text-3xl !font-semibold">Curator Marketplace</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">Match releases with independent playlists, blogs, radio, YouTube, influencers and music media. Credits buy review consideration only. Curators control every editorial decision.</p></div><div className="rounded-2xl border border-violet-500/25 bg-violet-500/[.06] px-4 py-3 text-right"><div className="text-[10px] uppercase tracking-wide text-neutral-500">Review credits</div><div className="text-2xl font-semibold">{wallet?.balance??"—"}</div><div className="text-[10px] text-neutral-500">Beta ledger · purchases not connected yet</div></div></div>
    <div className="mt-6 flex flex-wrap gap-2">{([['match','Find curators'],['submissions','My submissions'],['curator','Curator desk']] as const).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`rounded-full px-4 py-2 text-sm ${view===id?'bg-violet-600 text-white':'border border-neutral-300 dark:border-neutral-700'}`}>{label}</button>)}</div>
    {message&&<div className="mt-4 rounded-xl border border-violet-500/20 bg-violet-500/[.04] p-3 text-sm text-neutral-600 dark:text-neutral-300">{message}</div>}

    {view==="match"&&<div className="mt-5 space-y-4">
      <section className={panel}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.18em] text-violet-500">Audio Intelligence + SEO</div><h2 className="mt-1 text-xl font-semibold">Find editorial fits</h2><p className="mt-1 text-sm text-neutral-500">YSong combines release metadata, the Phase 22 report when handed in, and one reusable SEO snapshot. The score measures fit, not the chance of acceptance.</p></div>{initialIntelligence&&<span className="rounded-full border border-emerald-500/25 bg-emerald-500/10 px-3 py-1 text-xs text-emerald-500">Audio Intelligence attached</span>}</div>
        <div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="text-xs text-neutral-500">Release<select className={`${input} mt-1`} value={releaseId} onChange={e=>setReleaseId(e.target.value)}><option value="">Select release</option>{releases.map(r=><option key={r.id} value={r.id}>{r.artistName} · {r.title}</option>)}</select></label><label className="text-xs text-neutral-500">Track<select className={`${input} mt-1`} value={trackId} onChange={e=>setTrackId(e.target.value)}><option value="">Release-level match</option>{selectedRelease?.tracks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><button disabled={busy||!releaseId} onClick={buildMatches} className={`${primary} self-end`}>{busy?"Analyzing…":"Build curator matches"}</button></div>
      </section>
      {recs.map(rec=><section key={rec.channel.id} className={panel}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{rec.channel.name}</h3>{rec.profile.verified&&<span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] text-emerald-500">Verified</span>}<span className="rounded-full border border-neutral-300 dark:border-neutral-700 px-2 py-1 text-[10px]">{typeLabel(rec.profile.curatorType)}</span></div><div className="mt-1 text-sm text-neutral-500">{rec.profile.displayName}{rec.profile.organization?` · ${rec.profile.organization}`:""} · {rec.channel.platform}</div></div><div className="text-right"><div className="text-3xl font-semibold text-violet-500">{rec.match.score}</div><div className="text-[10px] uppercase text-neutral-500">fit / 100</div></div></div>
        <div className="mt-4 grid gap-3 md:grid-cols-4"><div><div className="text-[10px] uppercase text-neutral-500">Review cost</div><div className="font-semibold">{rec.channel.submissionCostCredits} credits</div></div><div><div className="text-[10px] uppercase text-neutral-500">Response rate</div><div className="font-semibold">{pct(rec.stats.responseRate)}</div></div><div><div className="text-[10px] uppercase text-neutral-500">Historical acceptance</div><div className="font-semibold">{rec.stats.responded?pct(rec.stats.acceptanceRate):'—'}</div></div><div><div className="text-[10px] uppercase text-neutral-500">Requested response</div><div className="font-semibold">{rec.channel.responseDays} days</div></div></div>
        <div className="mt-4 flex flex-wrap gap-2">{rec.match.reasons.map(x=><span key={x} className="rounded-full border border-emerald-500/20 bg-emerald-500/[.05] px-3 py-1 text-xs text-neutral-600 dark:text-neutral-300">{x}</span>)}</div>
        <textarea className={`${input} mt-4 min-h-20`} value={pitches[rec.channel.id]||""} onChange={e=>setPitches(v=>({...v,[rec.channel.id]:e.target.value}))} placeholder="Optional curator pitch: why this release fits their audience…"/>
        <div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div className="text-xs text-neutral-500">No guaranteed placement. Acceptance is an independent curator decision.</div><button disabled={busy||(wallet?.balance??0)<rec.channel.submissionCostCredits} onClick={()=>submit(rec)} className={primary}>Submit for review · {rec.channel.submissionCostCredits} credits</button></div>
      </section>)}
    </div>}

    {view==="submissions"&&<div className="mt-5 space-y-3">{!subs.length&&<div className={panel}>No curator submissions yet.</div>}{subs.map(s=><section key={s.id} className={panel}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{String(s.curator?.channelName||'Curator submission')}</h3><div className="text-sm text-neutral-500">{String(s.curator?.displayName||'')} · {String(s.curator?.platform||'')}</div></div><span className="rounded-full border border-neutral-300 dark:border-neutral-700 px-3 py-1 text-xs capitalize">{s.status.replaceAll('_',' ')}</span></div><div className="mt-3 grid gap-3 md:grid-cols-3 text-sm"><div><span className="text-neutral-500">Credits:</span> {s.creditsSpent}</div><div><span className="text-neutral-500">Placement:</span> {s.placementStatus}</div><div><span className="text-neutral-500">Submitted:</span> {new Date(s.submittedAt).toLocaleDateString()}</div></div>{typeof s.feedback?.summary==='string'&&s.feedback.summary&&<div className="mt-3 rounded-xl border border-neutral-200 dark:border-neutral-800 p-3 text-sm"><div className="text-[10px] uppercase text-neutral-500">Curator feedback</div>{s.feedback.summary}</div>}{s.placementStatus==='published'&&s.placementUrl&&<a className="mt-3 inline-block text-sm text-violet-500" href={s.placementUrl} target="_blank" rel="noreferrer">Open published placement ↗</a>}{s.status==='pending'&&<button className={`${btn} mt-3`} onClick={async()=>{await curatorApi.withdraw(s.id);await load();}}>Withdraw before review · refund credits</button>}</section>)}</div>}

    {view==="curator"&&<div className="mt-5 grid gap-4 xl:grid-cols-2"><div className="space-y-4"><section className={panel}><h2 className="text-xl font-semibold">Curator profile</h2><p className="mt-1 text-xs text-neutral-500">One YSong account can be both artist and curator. Activating a profile requires the editorial-independence acknowledgement.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input className={input} placeholder="Display name" value={profileForm.displayName} onChange={e=>setProfileForm(v=>({...v,displayName:e.target.value}))}/><input className={input} placeholder="Organization" value={profileForm.organization} onChange={e=>setProfileForm(v=>({...v,organization:e.target.value}))}/><select className={input} value={profileForm.curatorType} onChange={e=>setProfileForm(v=>({...v,curatorType:e.target.value}))}>{["playlist","blog","radio","youtube","influencer","music_media"].map(x=><option key={x} value={x}>{typeLabel(x)}</option>)}</select><select className={input} value={profileForm.status} onChange={e=>setProfileForm(v=>({...v,status:e.target.value}))}><option value="draft">Draft</option><option value="active">Active/listed</option><option value="paused">Paused</option></select><input className={`${input} md:col-span-2`} placeholder="Website" value={profileForm.websiteUrl} onChange={e=>setProfileForm(v=>({...v,websiteUrl:e.target.value}))}/><textarea className={`${input} md:col-span-2 min-h-24`} placeholder="What do you cover?" value={profileForm.bio} onChange={e=>setProfileForm(v=>({...v,bio:e.target.value}))}/></div><label className="mt-3 flex items-start gap-2 text-xs text-neutral-500"><input type="checkbox" checked={profileForm.editorialIndependenceAck} onChange={e=>setProfileForm(v=>({...v,editorialIndependenceAck:e.target.checked}))}/><span>I understand paid credits purchase review consideration only. I retain independent editorial control and will not sell guaranteed playlist/media placement.</span></label><button disabled={busy} onClick={saveProfile} className={`${primary} mt-4`}>Save curator profile</button></section>
      <section className={panel}><h2 className="text-xl font-semibold">Add a channel</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input className={input} placeholder="Channel / playlist name" value={channelForm.name} onChange={e=>setChannelForm(v=>({...v,name:e.target.value}))}/><input className={input} placeholder="Platform" value={channelForm.platform} onChange={e=>setChannelForm(v=>({...v,platform:e.target.value}))}/><input className={`${input} md:col-span-2`} placeholder="Channel URL" value={channelForm.url} onChange={e=>setChannelForm(v=>({...v,url:e.target.value}))}/><textarea className={`${input} md:col-span-2 min-h-20`} placeholder="Description" value={channelForm.description} onChange={e=>setChannelForm(v=>({...v,description:e.target.value}))}/><input className={input} placeholder="Genres: trance, gothic, symphonic" value={channelForm.genres} onChange={e=>setChannelForm(v=>({...v,genres:e.target.value}))}/><input className={input} placeholder="Moods: dark, cinematic" value={channelForm.moods} onChange={e=>setChannelForm(v=>({...v,moods:e.target.value}))}/><input className={input} placeholder="Sonic tags: female vocal, supersaw" value={channelForm.sonicTags} onChange={e=>setChannelForm(v=>({...v,sonicTags:e.target.value}))}/><input className={input} placeholder="Languages" value={channelForm.languages} onChange={e=>setChannelForm(v=>({...v,languages:e.target.value}))}/><input className={input} type="number" min="0" max="100" placeholder="Review credits" value={channelForm.submissionCostCredits} onChange={e=>setChannelForm(v=>({...v,submissionCostCredits:e.target.value}))}/><input className={input} type="number" min="1" max="30" placeholder="Response days" value={channelForm.responseDays} onChange={e=>setChannelForm(v=>({...v,responseDays:e.target.value}))}/></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={channelForm.acceptsExplicit} onChange={e=>setChannelForm(v=>({...v,acceptsExplicit:e.target.checked}))}/> Accept explicit releases</label><button disabled={busy||!profile} onClick={addChannel} className={`${primary} mt-4`}>Create channel</button></section>
      {channels.map(c=><section key={c.id} className={panel}><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{c.name}</h3><div className="text-sm text-neutral-500">{c.platform} · {c.submissionCostCredits} credits · {c.responseDays} day response target</div></div><span className={`text-xs ${c.active?'text-emerald-500':'text-neutral-500'}`}>{c.active?'Active':'Paused'}</span></div><div className="mt-3 flex flex-wrap gap-2">{c.genres.map(g=><span key={g} className="rounded-full border border-neutral-300 dark:border-neutral-700 px-2 py-1 text-xs">{g}</span>)}</div></section>)}</div>

      <div className="space-y-4"><section className={panel}><div className="text-[10px] uppercase tracking-wide text-neutral-500">Curator quality signals</div><div className="mt-3 grid grid-cols-2 gap-3"><div><div className="text-2xl font-semibold">{stats?pct(stats.responseRate):'—'}</div><div className="text-xs text-neutral-500">Response rate</div></div><div><div className="text-2xl font-semibold">{stats?.responded?pct(stats.acceptanceRate):'—'}</div><div className="text-xs text-neutral-500">Historical acceptance</div></div></div><p className="mt-3 text-xs text-neutral-500">Acceptance rate is descriptive history, not a promise or ranking shortcut. YSong reputation weights response behavior and sample size.</p></section>
      {desk.map(s=><section key={s.id} className={panel}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{submissionArtist(s)} · {submissionTitle(s)}</h3><div className="text-sm text-neutral-500">{s.channel?.name} · match {submissionMatchScore(s)}/100</div></div><span className="rounded-full border border-neutral-300 dark:border-neutral-700 px-3 py-1 text-xs capitalize">{s.status.replaceAll('_',' ')}</span></div>{s.pitch&&<div className="mt-3 rounded-xl bg-neutral-100 dark:bg-neutral-900 p-3 text-sm">{s.pitch}</div>}<div className="mt-3 flex flex-wrap gap-2">{s.status==='pending'&&<button className={btn} onClick={async()=>{await curatorApi.open(s.id);await load();}}>Open review</button>}{['pending','in_review'].includes(s.status)&&<><button className="rounded-xl bg-emerald-600 px-3 py-2 text-sm text-white" onClick={()=>respond(s.id,'accepted')}>Accept</button><button className="rounded-xl bg-rose-600 px-3 py-2 text-sm text-white" onClick={()=>respond(s.id,'rejected')}>Reject + feedback</button></>}{s.status==='accepted'&&s.placementStatus!=='published'&&<button className={btn} onClick={()=>markPlacement(s)}>Mark published placement</button>}{s.placementStatus==='published'&&s.placementUrl&&<a className="text-sm text-violet-500 self-center" href={s.placementUrl} target="_blank" rel="noreferrer">Open placement ↗</a>}</div></section>)}{!desk.length&&<section className={panel}>No submissions in your curator queue.</section>}</div></div>}

    <div className="mt-6 rounded-2xl border border-dashed border-neutral-300 dark:border-neutral-800 p-4 text-xs text-neutral-500">Phase 24 policy: marketplace credits buy review consideration, not acceptance and never guaranteed placement. YSong match scores describe metadata/editorial fit only. Purchase-provider billing is intentionally not claimed until a real payment integration exists.</div>
  </div></div>;
}
