import { useEffect, useState } from 'react';
import { apiGet, apiPost } from '../lib/authApi';
type Plan={id:string;name:string;monthlyPriceCents:number;quota:number|null;capabilities:Record<string,boolean>;available:boolean};
export default function Pricing(){
  const [plans,setPlans]=useState<Plan[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{void apiGet<{plans:Plan[]}>('/api/billing/catalog').then(r=>setPlans(r.plans)).catch(()=>setMessage('Plan catalog is awaiting configuration.'));},[]);
  async function choose(id:string){setBusy(true);setMessage('Starting secure checkout…');try{const storageKey=`ysong:checkout:${id}`;const key=sessionStorage.getItem(storageKey)??crypto.randomUUID();sessionStorage.setItem(storageKey,key);const r=await apiPost<{url:string}>('/api/billing/checkout',{planId:id,requestKey:key});const url=new URL(r.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw new Error('Invalid checkout destination');window.location.assign(url.href);}catch(e){setBusy(false);setMessage(e instanceof Error?e.message:'Checkout unavailable');}}
  return <main className="mx-auto max-w-5xl p-8 space-y-6"><h1 className="text-3xl">YSong plans</h1><p>Sign in before checkout. Payment details are handled by Stripe.</p><div className="grid gap-4 md:grid-cols-4">{plans.map(p=><section key={p.id} className="rounded-xl border p-4 space-y-3"><h2>{p.name}</h2><p>${(p.monthlyPriceCents/100).toFixed(2)} / month</p><p>{p.quota===null?'Generation allowance awaiting configuration':`${p.quota} monthly generation credits`}</p>{Object.entries(p.capabilities).filter(([,enabled])=>enabled).map(([name])=><p key={name}>{name}</p>)}{p.id==='free'?<a href="/signup">Create account</a>:<button disabled={busy||!p.available} onClick={()=>void choose(p.id)}>{p.available?'Choose plan':'Not yet available'}</button>}</section>)}</div>{message&&<p role="status">{message}</p>}</main>;
}
