import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { publicPromotionUrl, type PromotionCampaign } from "../tools/promotion/api";

function visitorId(){
  const key="ysong_promo_vid"; try{let v=localStorage.getItem(key);if(!v){v=crypto.randomUUID();localStorage.setItem(key,v);}return v;}catch{return crypto.randomUUID();}
}
async function postPublic(slug:string,path:string,body:Record<string,unknown>){const res=await fetch(publicPromotionUrl(`/api/promotion/public/${encodeURIComponent(slug)}${path}`),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!res.ok){const d=await res.json().catch(()=>({}));throw new Error(String(d?.error||`HTTP ${res.status}`));}return res.json().catch(()=>({}));}

export default function PromotionLanding(){
  const {slug=""}=useParams(); const [campaign,setCampaign]=useState<PromotionCampaign|null>(null); const [qrUrl,setQrUrl]=useState(""); const [error,setError]=useState(""); const [email,setEmail]=useState(""); const [consent,setConsent]=useState(false); const [submitted,setSubmitted]=useState(false); const [busy,setBusy]=useState(false); const vid=useMemo(()=>visitorId(),[]); const attribution=useMemo(()=>{const q=new URLSearchParams(window.location.search);return {utmSource:q.get("utm_source")||"",utmMedium:q.get("utm_medium")||"",utmCampaign:q.get("utm_campaign")||"",utmContent:q.get("utm_content")||"",adCampaignId:q.get("ysong_ad_campaign")||"",creativeId:q.get("ysong_creative")||""};},[]);
  useEffect(()=>{let live=true;(async()=>{try{const res=await fetch(publicPromotionUrl(`/api/promotion/public/${encodeURIComponent(slug)}`));if(!res.ok)throw new Error("Campaign not found.");const data=await res.json();if(!live)return;setCampaign(data.campaign);setQrUrl(data.qrUrl||"");const q=new URLSearchParams(window.location.search); void postPublic(slug,"/events",{eventType:"view",visitorId:vid,metadata:{utmSource:q.get("utm_source")||"",utmMedium:q.get("utm_medium")||"",utmCampaign:q.get("utm_campaign")||"",utmContent:q.get("utm_content")||"",adCampaignId:q.get("ysong_ad_campaign")||"",creativeId:q.get("ysong_creative")||""}}).catch(()=>{});}catch(e){if(live)setError(e instanceof Error?e.message:"Campaign unavailable.");}})();return()=>{live=false;};},[slug,vid]);
  async function capture(){if(!campaign||!email||!consent)return;setBusy(true);setError("");try{await postPublic(slug,"/fans",{email,consent:true,visitorId:vid,source:"landing_page",provider:campaign.kind==="presave"?"presave":"release",...attribution});setSubmitted(true);}catch(e){setError(e instanceof Error?e.message:"Could not save email.");}finally{setBusy(false);}}
  if(error&&!campaign)return <main className="min-h-screen bg-neutral-950 text-white grid place-items-center p-6"><div className="max-w-lg text-center"><div className="text-5xl">♪</div><h1 className="mt-5 text-2xl font-semibold">This YSong campaign is unavailable.</h1><p className="mt-2 text-neutral-400">{error}</p></div></main>;
  if(!campaign)return <main className="min-h-screen bg-neutral-950 text-white grid place-items-center"><div className="text-sm text-neutral-500">Loading release…</div></main>;
  const attr=`&ac=${encodeURIComponent(attribution.adCampaignId)}&cr=${encodeURIComponent(attribution.creativeId)}`;
  const artwork=campaign.hasArtwork?publicPromotionUrl(`/api/promotion/public/${encodeURIComponent(campaign.slug)}/artwork`):"";
  return <main className="min-h-screen bg-neutral-950 text-white">
    <div className="mx-auto max-w-4xl px-5 py-10 md:py-16">
      <div className="grid gap-8 md:grid-cols-[320px_1fr] md:items-start">
        <div>{artwork?<img src={artwork} alt={`${campaign.title} artwork`} className="aspect-square w-full rounded-3xl object-cover shadow-2xl shadow-black/50"/>:<div className="aspect-square w-full rounded-3xl bg-gradient-to-br from-violet-600/35 to-fuchsia-500/10 grid place-items-center text-7xl">♪</div>}{qrUrl&&<div className="mt-4 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-3"><img src={qrUrl} alt="QR code" className="h-16 w-16 rounded bg-white p-1"/><div><div className="text-xs font-medium">Share this release</div><div className="mt-1 text-[11px] text-neutral-500">The QR points directly to this YSong campaign.</div></div></div>}</div>
        <section><div className="text-[11px] uppercase tracking-[.25em] text-violet-400">{campaign.kind==="presave"?"Pre-save campaign":campaign.kind==="release"?"Release":"Smart Link"}</div><h1 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">{campaign.title}</h1>{campaign.artistName&&<div className="mt-2 text-xl text-neutral-300">{campaign.artistName}</div>}{campaign.headline&&<p className="mt-4 text-lg text-neutral-200">{campaign.headline}</p>}{campaign.description&&<p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-neutral-400">{campaign.description}</p>}{campaign.releaseDate&&<div className="mt-4 text-xs text-neutral-500">Release date · {new Date(campaign.releaseDate).toLocaleDateString()}</div>}
          <div className="mt-7 space-y-3">{campaign.destinations.map(d=><a key={d.id||d.url} href={publicPromotionUrl(`/api/promotion/r/${encodeURIComponent(campaign.slug)}/${encodeURIComponent(d.id||"")}?v=${encodeURIComponent(vid)}${attr}`)} className="flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.06] px-5 py-4 text-sm font-medium transition hover:border-violet-400/50 hover:bg-violet-500/10"><span>{d.label}</span><span className="text-xs text-neutral-500">{d.platform} →</span></a>)}</div>
          <div className="mt-8 rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="font-medium">{campaign.kind==="presave"?"Get the release reminder":"Stay connected"}</div><p className="mt-1 text-xs text-neutral-500">Your email goes to this artist's YSong campaign list. Consent is required and is recorded with the signup.</p>{submitted?<div className="mt-4 rounded-xl bg-emerald-500/10 px-4 py-3 text-sm text-emerald-300">You're on the list. ✓</div>:<><div className="mt-4 flex gap-2"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm outline-none focus:border-violet-400"/><button disabled={busy||!email||!consent} onClick={()=>void capture()} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold disabled:opacity-40">Join</button></div><label className="mt-3 flex items-start gap-2 text-[11px] text-neutral-500"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-0.5"/><span>I consent to this artist storing my email for release and music updates.</span></label></>}{error&&<div className="mt-2 text-xs text-red-400">{error}</div>}</div>
        </section>
      </div><div className="mt-12 text-center text-[11px] text-neutral-600">Powered by YSong Promotion Center</div>
    </div>
  </main>;
}
