import { useEffect, useMemo, useState } from "react";
import WaveformPicker from "./WaveformPicker";
import AudienceCampaignSetup from "./AudienceCampaignSetup";
import AdCampaignAnalytics from "./AdCampaignAnalytics";
import PromotionIntelligence from "./PromotionIntelligence";
import { promotionApi, type AdCampaign, type AdCreative, type AudioSnippet, type BackgroundVideo, type CreativeLibrary, type PromotionCampaign, type PromotionHealth, type PromotionRelease, type StockVideo } from "./api";

const panel="rounded-2xl border border-neutral-200 bg-white/80 p-5 dark:border-neutral-800 dark:bg-neutral-900/55";
const input="w-full rounded-xl border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-violet-500 dark:border-neutral-700 dark:bg-neutral-950";
const chip="rounded-full border border-neutral-300 px-2.5 py-1 text-xs dark:border-neutral-700";
type Step="music"|"audio"|"videos"|"generate"|"setup"|"analytics"|"intelligence";

function fmtSecs(v:number|null|undefined){if(!v&&v!==0)return "";const n=Math.max(0,Number(v)||0);return `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,"0")}`;}
function trackOf(releases:PromotionRelease[],id:string|null|undefined){for(const release of releases){const track=release.tracks.find(t=>t.id===id);if(track)return {release,track};}return null;}

export default function AdCampaignStudio({campaigns,releases,health,onMessage}:{campaigns:PromotionCampaign[];releases:PromotionRelease[];health:PromotionHealth|null;onMessage:(value:string)=>void}){
  const [ads,setAds]=useState<AdCampaign[]>([]); const [selected,setSelected]=useState<AdCampaign|null>(null); const [snippets,setSnippets]=useState<AudioSnippet[]>([]); const [backgrounds,setBackgrounds]=useState<BackgroundVideo[]>([]); const [creatives,setCreatives]=useState<AdCreative[]>([]); const [libraries,setLibraries]=useState<CreativeLibrary[]>([]);
  const [step,setStep]=useState<Step>("music"); const [busy,setBusy]=useState(false); const [newMode,setNewMode]=useState(false);
  const [smartId,setSmartId]=useState(""); const [releaseId,setReleaseId]=useState(""); const [trackId,setTrackId]=useState(""); const [name,setName]=useState(""); const [genre,setGenre]=useState(""); const [genreSource,setGenreSource]=useState<"ysong"|"user">("ysong");
  const [audioUrl,setAudioUrl]=useState(""); const [clipStart,setClipStart]=useState(0); const [clipDuration,setClipDuration]=useState(30); const [clipLabel,setClipLabel]=useState("");
  const [chosenBackgrounds,setChosenBackgrounds]=useState<string[]>([]); const [chosenSnippets,setChosenSnippets]=useState<string[]>([]); const [libraryId,setLibraryId]=useState<string|null>(null); const [newLibraryName,setNewLibraryName]=useState(""); const [backgroundUrls,setBackgroundUrls]=useState<Record<string,string>>({}); const [creativeUrls,setCreativeUrls]=useState<Record<string,{vertical?:string;feed?:string}>>({});
  const [stockQuery,setStockQuery]=useState(""); const [stockResults,setStockResults]=useState<StockVideo[]>([]); const [stockBusy,setStockBusy]=useState(false); const [stockError,setStockError]=useState(""); const [stockNextPage,setStockNextPage]=useState<number|null>(null); const [stockTotal,setStockTotal]=useState(0);

  const selectedTrack=useMemo(()=>trackOf(releases,selected?.sourceTrackId||trackId),[releases,selected?.sourceTrackId,trackId]);
  const selectedSmart=campaigns.find(c=>c.id===(selected?.campaignId||smartId))||null;
  const selectedRelease=releases.find(r=>r.id===releaseId)||selectedTrack?.release||null;
  const renderReady=health?.render.available&&health.render.h264&&health.render.aac;

  async function loadBase(){try{const [a,b,l]=await Promise.all([promotionApi.adCampaigns(),promotionApi.backgrounds(),promotionApi.libraries()]);setAds(a.adCampaigns);setBackgrounds(b.backgroundVideos);setLibraries(l.libraries);}catch(e){onMessage(e instanceof Error?e.message:"Ad Campaign Studio could not load.");}}
  useEffect(()=>{void loadBase();},[]); // eslint-disable-line react-hooks/exhaustive-deps

  async function openAd(id:string){setBusy(true);try{const out=await promotionApi.adCampaign(id);setSelected(out.adCampaign);setSnippets(out.snippets);setCreatives(out.creatives);setChosenSnippets(out.snippets.map(s=>s.id));setNewMode(false);setStep("music");}catch(e){onMessage(e instanceof Error?e.message:"Could not load ad campaign.");}finally{setBusy(false);}}

  useEffect(()=>{
    if(!selected)return; const found=trackOf(releases,selected.sourceTrackId); if(!found?.track.audioObjectKey){setAudioUrl("");return;} let cancelled=false;
    void promotionApi.signedUrl(found.track.audioObjectKey).then(r=>{if(!cancelled)setAudioUrl(r.url);}).catch(()=>{if(!cancelled)setAudioUrl("");}); return()=>{cancelled=true;};
  },[selected,releases]);

  useEffect(()=>{
    if(!selected||!creatives.some(c=>c.status==="queued"||c.status==="rendering"))return;
    const timer=window.setInterval(()=>{void promotionApi.creatives(selected.id).then(out=>setCreatives(out.creatives)).catch(()=>{});},2000); return()=>window.clearInterval(timer);
  },[selected,creatives]);

  useEffect(()=>{
    let cancelled=false;
    for(const background of backgrounds){
      if(backgroundUrls[background.id])continue;
      void promotionApi.signedUrl(background.objectKey).then(out=>{if(!cancelled)setBackgroundUrls(prev=>({...prev,[background.id]:out.url}));}).catch(()=>{});
    }
    return()=>{cancelled=true;};
  },[backgrounds]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(()=>{
    let cancelled=false; const ready=creatives.filter(c=>c.status==="ready");
    for(const c of ready){if(creativeUrls[c.id]?.vertical&&creativeUrls[c.id]?.feed)continue;void Promise.all([c.objectKey916?promotionApi.signedUrl(c.objectKey916):Promise.resolve(null),c.objectKey43?promotionApi.signedUrl(c.objectKey43):Promise.resolve(null)]).then(([v,f])=>{if(cancelled)return;setCreativeUrls(prev=>({...prev,[c.id]:{vertical:v?.url,feed:f?.url}}));}).catch(()=>{});}return()=>{cancelled=true;};
  },[creatives]); // eslint-disable-line react-hooks/exhaustive-deps

  function beginNew(){const smart=campaigns.find(c=>c.status==="active")||campaigns[0];setSmartId(smart?.id||"");const r=releases.find(x=>x.id===smart?.sourceReleaseId)||releases[0];setReleaseId(r?.id||"");const t=r?.tracks[0];setTrackId(t?.id||"");setGenre(t?.genre||r?.genre||smart?.genre||"");setGenreSource("ysong");setName(`${t?.title||smart?.title||"New release"} · Meta campaign`);setNewMode(true);setSelected(null);setStep("music");}
  function pickRelease(id:string){setReleaseId(id);const r=releases.find(x=>x.id===id);const t=r?.tracks[0];setTrackId(t?.id||"");setGenre(t?.genre||r?.genre||"");setGenreSource("ysong");if(t)setName(`${t.title} · Meta campaign`);}
  function pickTrack(id:string){setTrackId(id);const found=trackOf(releases,id);if(found){setGenre(found.track.genre||found.release.genre||genre);setGenreSource("ysong");setName(`${found.track.title} · Meta campaign`);}}

  async function createAd(){if(!smartId||!trackId||!name.trim())return;setBusy(true);try{const out=await promotionApi.createAdCampaign({campaignId:smartId,sourceTrackId:trackId,name:name.trim(),goal:"song_growth",genre,genreSource,placements:["facebook","instagram"],targeting:{countries:[],ageMin:18,ageMax:65,gender:"all",interests:[]},adHeadline:"Listen now"});setAds(v=>[out.adCampaign,...v]);await openAd(out.adCampaign.id);onMessage("Ad campaign draft created. No money is spent and nothing is sent to Meta yet.");}catch(e){onMessage(e instanceof Error?e.message:"Could not create ad campaign.");}finally{setBusy(false);}}

  async function addClip(){if(!selected)return;setBusy(true);try{const out=await promotionApi.addSnippet(selected.id,{sourceTrackId:selected.sourceTrackId,startSeconds:clipStart,durationSeconds:clipDuration,label:clipLabel||`Clip ${snippets.length+1}`});setSnippets(v=>[...v,out.snippet]);setChosenSnippets(v=>[...new Set([...v,out.snippet.id])]);setClipLabel("");onMessage(`Saved ${out.snippet.durationSeconds.toFixed(1)} second audio clip.`);}catch(e){onMessage(e instanceof Error?e.message:"Could not save audio clip.");}finally{setBusy(false);}}
  async function removeClip(id:string){if(!selected)return;setBusy(true);try{await promotionApi.deleteSnippet(selected.id,id);setSnippets(v=>v.filter(x=>x.id!==id));setChosenSnippets(v=>v.filter(x=>x!==id));}catch(e){onMessage(e instanceof Error?e.message:"Could not remove clip.");}finally{setBusy(false);}}

  async function uploadVideos(files:FileList|null){if(!files?.length)return;setBusy(true);try{for(const file of Array.from(files)){const up=await promotionApi.upload(file);const reg=await promotionApi.registerBackground(up.objectKey,libraryId);setBackgrounds(v=>[reg.backgroundVideo,...v]);setChosenBackgrounds(v=>v.length<5?[...v,reg.backgroundVideo.id]:v);}onMessage("Background video upload complete. Its original audio will not be used in generated ads.");}catch(e){onMessage(e instanceof Error?e.message:"Video upload failed.");}finally{setBusy(false);}}
  async function searchStock(page=1,append=false){const q=stockQuery.trim();if(q.length<2)return;setStockBusy(true);setStockError("");try{const out=await promotionApi.stockVideos(q,{provider:"pexels",orientation:"portrait",page,perPage:30});setStockResults(v=>append?[...v,...out.videos.filter(item=>!v.some(x=>x.provider===item.provider&&x.id===item.id))]:out.videos);setStockNextPage(out.nextPage);setStockTotal(out.totalResults);}catch(e){setStockError(e instanceof Error?e.message:"Stock video search failed.");if(!append)setStockResults([]);}finally{setStockBusy(false);}}
  async function importStock(item:StockVideo){setStockBusy(true);setStockError("");try{const out=await promotionApi.importStockVideo({provider:item.provider,id:item.id,libraryId});setBackgrounds(v=>[out.backgroundVideo,...v]);setChosenBackgrounds(v=>v.length<5?[...v,out.backgroundVideo.id]:v);onMessage(`Imported ${item.contributor.name}'s Pexels clip into this YSong creative library.`);}catch(e){setStockError(e instanceof Error?e.message:"Stock video import failed.");}finally{setStockBusy(false);}}
  function toggleBackground(id:string){setChosenBackgrounds(v=>v.includes(id)?v.filter(x=>x!==id):v.length<5?[...v,id]:v);}
  function toggleSnippet(id:string){setChosenSnippets(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v);}
  async function createLibrary(){const n=newLibraryName.trim();if(!n)return;try{const out=await promotionApi.createLibrary(n);setLibraries(v=>[out.library,...v]);setLibraryId(out.library.id);setNewLibraryName("");}catch(e){onMessage(e instanceof Error?e.message:"Could not create library.");}}
  async function render(){if(!selected||!chosenSnippets.length||!chosenBackgrounds.length)return;setBusy(true);try{const out=await promotionApi.renderBatch(selected.id,{snippetIds:chosenSnippets,backgroundVideoIds:chosenBackgrounds,libraryId});setCreatives(prev=>{const ids=new Set(out.queued.map(x=>x.id));return [...prev.filter(x=>!ids.has(x.id)),...out.queued];});setStep("generate");onMessage(`${chosenSnippets.length} audio clip${chosenSnippets.length===1?"":"s"} × ${chosenBackgrounds.length} background${chosenBackgrounds.length===1?"":"s"} queued. FFmpeg is rendering ${chosenSnippets.length*chosenBackgrounds.length} ad creative${chosenSnippets.length*chosenBackgrounds.length===1?"":"s"}.`);}catch(e){onMessage(e instanceof Error?e.message:"Render queue failed.");}finally{setBusy(false);}}
  async function toggleCreative(c:AdCreative){if(!selected)return;try{const out=await promotionApi.patchCreative(selected.id,c.id,{selected:!c.selected});setCreatives(v=>v.map(x=>x.id===c.id?out.creative:x));}catch(e){onMessage(e instanceof Error?e.message:"Could not update creative.");}}

  const combinationCount=chosenSnippets.length*chosenBackgrounds.length;
  const navSteps:[Step,string][]=[["music","1 · Music"],["audio","2 · Audio clips"],["videos","3 · Backgrounds"],["generate","4 · Generate"],["setup","5 · Audience & Campaign"],["analytics","6 · Analytics"],["intelligence","7 · Intelligence"]];

  return <div className="mt-6 grid gap-5 xl:grid-cols-[300px_minmax(0,1fr)]">
    <aside className={panel}><div className="flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-[.18em] text-violet-500">Paid campaigns</div><h2 className="mt-1 text-lg font-semibold">Ad Campaigns</h2></div><button onClick={beginNew} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-semibold text-white">+ New</button></div>
      <div className="mt-4 space-y-2">{ads.length?ads.map(a=><button key={a.id} onClick={()=>void openAd(a.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id===a.id?"border-violet-500/60 bg-violet-500/5":"border-neutral-200 dark:border-neutral-800"}`}><div className="font-medium">{a.name}</div><div className="mt-1 flex items-center justify-between text-[11px] text-neutral-500"><span>{a.genre||"Genre not set"}</span><span>{a.status}</span></div></button>):<div className="rounded-xl border border-dashed border-neutral-300 p-5 text-center text-xs text-neutral-500 dark:border-neutral-700">No paid-ad drafts yet.</div>}</div>
      <div className="mt-5 rounded-xl border border-neutral-200 p-3 text-xs dark:border-neutral-800"><div className="font-semibold">Render engine</div><div className={`mt-1 ${renderReady?"text-emerald-500":"text-amber-500"}`}>{renderReady?"FFmpeg ready":"FFmpeg unavailable"}</div><div className="mt-1 break-words text-[10px] text-neutral-500">{health?.render.version||health?.render.error||"Checking runtime…"}</div></div>
    </aside>

    <section className={panel}>
      {newMode?<div><div className="text-xs uppercase tracking-widest text-violet-500">New paid campaign</div><h2 className="mt-1 text-2xl font-semibold">Pick the music and its Smart Link</h2><p className="mt-2 text-sm text-neutral-500">The ad CTA will go to the YSong Smart Link, not directly to one streaming provider.</p>
        <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs text-neutral-500">YSong Smart Link<select className={input} value={smartId} onChange={e=>setSmartId(e.target.value)}><option value="">Select campaign…</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.artistName} · {c.title} · {c.status}</option>)}</select></label><label className="text-xs text-neutral-500">Release<select className={input} value={releaseId} onChange={e=>pickRelease(e.target.value)}><option value="">Select release…</option>{releases.map(r=><option key={r.id} value={r.id}>{r.artistName} · {r.title}</option>)}</select></label><label className="text-xs text-neutral-500">Track<select className={input} value={trackId} onChange={e=>pickTrack(e.target.value)}><option value="">Select track…</option>{selectedRelease?.tracks.map(t=><option key={t.id} value={t.id}>{t.trackNumber}. {t.title}</option>)}</select></label><label className="text-xs text-neutral-500">Genre<input className={input} value={genre} onChange={e=>{setGenre(e.target.value);setGenreSource("user");}} placeholder="YSong genre or manual override"/></label><label className="text-xs text-neutral-500 md:col-span-2">Campaign name<input className={input} value={name} onChange={e=>setName(e.target.value)}/></label></div>
        <div className="mt-4 rounded-xl border border-neutral-200 p-3 text-xs dark:border-neutral-800"><b>Smart Link destinations:</b> {campaigns.find(c=>c.id===smartId)?.destinations.map(d=>d.platform).join(" · ")||"Select a Smart Link"}</div><button disabled={busy||!smartId||!trackId||!name.trim()} onClick={()=>void createAd()} className="mt-5 rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Create ad campaign draft</button></div>
      :!selected?<div className="grid min-h-96 place-items-center text-center text-sm text-neutral-500"><div><div className="text-lg font-semibold text-neutral-800 dark:text-neutral-200">Select an ad campaign or create one.</div><div className="mt-1">Nothing is published or charged from this screen.</div></div></div>
      :<div>
        <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs uppercase tracking-widest text-violet-500">{selected.status}</div><h2 className="mt-1 text-2xl font-semibold">{selected.name}</h2><div className="text-sm text-neutral-500">{selectedTrack?.release.artistName} · {selectedTrack?.track.title} {selected.genre?`· ${selected.genre}`:""}</div></div><div className="rounded-xl border border-neutral-200 px-3 py-2 text-xs dark:border-neutral-800">CTA → <b>{selectedSmart?.title||"YSong Smart Link"}</b></div></div>
        <div className="mt-5 flex flex-wrap gap-2">{navSteps.map(([key,label])=><button key={key} onClick={()=>setStep(key)} className={`${chip} ${step===key?"border-violet-500 bg-violet-500/10 text-violet-500":""}`}>{label}</button>)}</div>

        {step==="music"&&<div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="text-sm font-semibold">Music source</div><div className="mt-3 text-sm">{selectedTrack?.track.title||"Track unavailable"}</div><div className="text-xs text-neutral-500">{selectedTrack?.release.title} · {fmtSecs(selectedTrack?.track.durationSeconds)}</div><div className="mt-3 flex flex-wrap gap-2"><span className={chip}>Genre: {selected.genre||"unset"}</span><span className={chip}>Source: {selected.genreSource}</span></div></div><div className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="text-sm font-semibold">Smart Link destination</div><div className="mt-2 text-sm">{selectedSmart?.publicUrl||"Missing Smart Link"}</div><div className="mt-3 flex flex-wrap gap-2">{selectedSmart?.destinations.map(d=><span key={d.id||d.url} className={chip}>{d.platform}</span>)}</div><p className="mt-3 text-xs text-neutral-500">The sponsored ad's Listen Now button will point here. Fans choose their service after clicking.</p></div></div>}

        {step==="audio"&&<div className="mt-5"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold">Audio snippets</h3><p className="text-xs text-neutral-500">Save up to three sections from the full YSong master.</p></div><span className={chip}>{snippets.length}/3</span></div>{audioUrl?<div className="mt-4"><WaveformPicker audioUrl={audioUrl} durationHint={Number(selectedTrack?.track.durationSeconds||0)} start={clipStart} duration={clipDuration} onChange={(s,d)=>{setClipStart(s);setClipDuration(d);}}/><div className="mt-3 flex gap-2"><input className={input} value={clipLabel} onChange={e=>setClipLabel(e.target.value)} placeholder={`Clip ${snippets.length+1} label (optional)`}/><button disabled={busy||snippets.length>=3} onClick={()=>void addClip()} className="whitespace-nowrap rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Save clip</button></div></div>:<div className="mt-4 rounded-xl border border-dashed border-neutral-300 p-6 text-center text-sm text-neutral-500 dark:border-neutral-700">Source audio is not available for waveform selection.</div>}
          <div className="mt-4 grid gap-2 md:grid-cols-3">{snippets.map((s,i)=><div key={s.id} className={`rounded-xl border p-3 ${chosenSnippets.includes(s.id)?"border-violet-500/60":"border-neutral-200 dark:border-neutral-800"}`}><button onClick={()=>toggleSnippet(s.id)} className="w-full text-left"><div className="text-sm font-semibold">{s.label||`Clip ${i+1}`}</div><div className="mt-1 text-xs text-neutral-500">{fmtSecs(s.startSeconds)} → {fmtSecs(s.startSeconds+s.durationSeconds)} · {s.durationSeconds.toFixed(1)}s</div></button><button onClick={()=>void removeClip(s.id)} className="mt-3 text-xs text-red-500">Delete</button></div>)}</div></div>}

        {step==="videos"&&<div className="mt-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-lg font-semibold">Background Reel library</h3><p className="text-xs text-neutral-500">Choose up to five short videos. Their original audio is discarded during rendering.</p></div><label className="cursor-pointer rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">Upload your own<input className="hidden" type="file" accept="video/mp4,video/quicktime,video/webm" multiple onChange={e=>void uploadVideos(e.target.files)}/></label></div>
          <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><select className={input} value={libraryId||""} onChange={e=>setLibraryId(e.target.value||null)}><option value="">No creative library</option>{libraries.map(l=><option key={l.id} value={l.id}>{l.name} ({l.creativeCount})</option>)}</select><div className="flex gap-2"><input className={input} value={newLibraryName} onChange={e=>setNewLibraryName(e.target.value)} placeholder="New library name"/><button onClick={()=>void createLibrary()} className="rounded-xl border border-neutral-300 px-3 text-xs dark:border-neutral-700">Create</button></div></div>

          <div className="mt-5 rounded-2xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-sm font-semibold">Search stock Reels</div><p className="mt-1 text-xs text-neutral-500">Search Pexels live. YSong imports only the clips you choose instead of copying an entire stock catalog.</p></div><a href="https://www.pexels.com/" target="_blank" rel="noreferrer" className="text-xs text-violet-500 underline">Videos provided by Pexels</a></div>
            {health?.stock?.providers?.pexels?.configured===false?<div className="mt-3 rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-700 dark:text-amber-300">Pexels search is not configured on this server yet. Add the server-side PEXELS_API_KEY. User uploads still work.</div>:<><div className="mt-3 flex gap-2"><input className={input} value={stockQuery} onChange={e=>setStockQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void searchStock(1,false);}}} placeholder="Search: gothic cathedral, cyberpunk dancer, moon, concert crowd…"/><button disabled={stockBusy||stockQuery.trim().length<2} onClick={()=>void searchStock(1,false)} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{stockBusy?"Searching…":"Search"}</button></div>{stockError&&<div className="mt-2 text-xs text-red-500">{stockError}</div>}
              {!!stockResults.length&&<><div className="mt-3 text-xs text-neutral-500">Showing {stockResults.length.toLocaleString()} of approximately {stockTotal.toLocaleString()} matching Pexels videos. Only clips 60 seconds or shorter are offered for ad backgrounds.</div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{stockResults.map(item=><div key={`${item.provider}:${item.id}`} className="overflow-hidden rounded-xl border border-neutral-200 dark:border-neutral-800"><video className="aspect-[9/16] max-h-72 w-full bg-black object-cover" src={item.previewVideoUrl||undefined} poster={item.previewImage||undefined} muted loop playsInline controls preload="none"/><div className="p-3"><div className="flex items-center justify-between gap-2"><div className="text-xs font-medium">{fmtSecs(item.durationSeconds)} · {item.width}×{item.height}</div><button disabled={stockBusy} onClick={()=>void importStock(item)} className="rounded-lg bg-violet-600 px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-40">Import</button></div><div className="mt-2 text-[11px] text-neutral-500">Video by <a href={item.contributor.url||item.pageUrl} target="_blank" rel="noreferrer" className="underline">{item.contributor.name}</a> on Pexels</div></div></div>)}</div>{stockNextPage&&<button disabled={stockBusy} onClick={()=>void searchStock(stockNextPage,true)} className="mt-3 w-full rounded-xl border border-neutral-300 px-3 py-2 text-sm dark:border-neutral-700">Load more Pexels videos</button>}</>}</>}
          </div>

          <div className="mt-5 flex items-center justify-between"><div><div className="text-sm font-semibold">Imported / uploaded backgrounds</div><div className="text-xs text-neutral-500">Click up to five for this render batch.</div></div><span className={chip}>{chosenBackgrounds.length}/5 selected</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{backgrounds.map(v=><button key={v.id} onClick={()=>toggleBackground(v.id)} className={`rounded-xl border p-3 text-left ${chosenBackgrounds.includes(v.id)?"border-violet-500 bg-violet-500/5":"border-neutral-200 dark:border-neutral-800"}`}><div className="aspect-[9/16] max-h-52 overflow-hidden rounded-lg bg-black">{backgroundUrls[v.id]?<video className="h-full w-full object-cover" src={backgroundUrls[v.id]} muted playsInline preload="metadata"/>:<div className="grid h-full place-items-center px-3 text-center text-xs text-neutral-400">{v.originalName}</div>}</div><div className="mt-2 text-sm font-medium truncate">{v.originalName}</div><div className="text-xs text-neutral-500">{fmtSecs(v.durationSeconds)} · {v.width||"?"}×{v.height||"?"}</div>{String(v.metadata?.source||"")==="stock"&&<div className="mt-1 text-[10px] text-violet-500">Pexels stock import</div>}</button>)}</div>{!backgrounds.length&&<div className="mt-4 rounded-xl border border-dashed border-neutral-300 p-8 text-center text-sm text-neutral-500 dark:border-neutral-700">Search Pexels or upload your own short videos to build the creative combinations.</div>}</div>}

        {step==="generate"&&<div className="mt-5"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-neutral-200 p-4 text-center dark:border-neutral-800"><div className="text-2xl font-semibold">{chosenSnippets.length}</div><div className="text-xs text-neutral-500">audio clips</div></div><div className="rounded-xl border border-neutral-200 p-4 text-center dark:border-neutral-800"><div className="text-2xl font-semibold">{chosenBackgrounds.length}</div><div className="text-xs text-neutral-500">backgrounds</div></div><div className="rounded-xl border border-violet-500/40 bg-violet-500/5 p-4 text-center"><div className="text-2xl font-semibold">{combinationCount}</div><div className="text-xs text-neutral-500">generated ads</div></div></div><button disabled={busy||!renderReady||combinationCount<1||combinationCount>15} onClick={()=>void render()} className="mt-4 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Generate {combinationCount||""} ad video{combinationCount===1?"":"s"}</button>
          <div className="mt-5 grid gap-4 lg:grid-cols-2">{creatives.map((c,i)=>{const urls=creativeUrls[c.id]||{};return <div key={c.id} className={`rounded-2xl border p-4 ${c.selected?"border-violet-500/45":"border-neutral-200 opacity-65 dark:border-neutral-800"}`}><div className="flex items-center justify-between"><div><div className="text-sm font-semibold">Creative {i+1}</div><div className="text-xs text-neutral-500">{c.status}{c.durationSeconds?` · ${c.durationSeconds.toFixed(1)}s`:""}</div></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={c.selected} onChange={()=>void toggleCreative(c)}/> Use in campaign</label></div>{c.status==="ready"?<div className="mt-3 grid grid-cols-[.56fr_1fr] gap-3"><div><div className="mb-1 text-[10px] uppercase text-neutral-500">9:16 Reels / Stories</div>{urls.vertical?<video className="aspect-[9/16] w-full rounded-lg bg-black object-contain" src={urls.vertical} controls preload="metadata"/>:<div className="aspect-[9/16] rounded-lg bg-black"/>}</div><div><div className="mb-1 text-[10px] uppercase text-neutral-500">4:3 Feed</div>{urls.feed?<video className="aspect-[4/3] w-full rounded-lg bg-black object-contain" src={urls.feed} controls preload="metadata"/>:<div className="aspect-[4/3] rounded-lg bg-black"/>}</div></div>:c.status==="failed"?<div className="mt-3 rounded-lg bg-red-500/10 p-3 text-xs text-red-500">{c.renderError||"Render failed."}<button onClick={async()=>{if(selected){await promotionApi.retryCreative(selected.id,c.id);const out=await promotionApi.creatives(selected.id);setCreatives(out.creatives);}}} className="ml-2 underline">Retry</button></div>:<div className="mt-3 rounded-lg border border-dashed border-neutral-300 p-8 text-center text-xs text-neutral-500 dark:border-neutral-700">FFmpeg {c.status}…</div>}</div>;})}</div></div>}

        {step==="setup"&&selected&&<AudienceCampaignSetup ad={selected} smartLink={selectedSmart} health={health} creatives={creatives} creativeUrls={creativeUrls} interestSeeds={[selected.genre,selectedTrack?.track.genre||"",selectedTrack?.release.genre||"",...(Array.isArray(selectedTrack?.track.tags)?selectedTrack.track.tags.filter((x):x is string=>typeof x==="string"):[])].filter(Boolean)} onSaved={(next)=>{setSelected(next);setAds(v=>v.map(x=>x.id===next.id?next:x));}} onMessage={onMessage}/>}
        {step==="analytics"&&selected&&<AdCampaignAnalytics ad={selected} onMessage={onMessage}/>}
        {step==="intelligence"&&selected&&<PromotionIntelligence ad={selected} onMessage={onMessage}/>}
      </div>}
    </section>
  </div>;
}
