import { useEffect, useMemo, useState } from "react";
import { promotionApi, type AdCampaign, type PaidAdAnalytics, type PaidCreativeAnalytics } from "./api";

const panel="rounded-2xl border border-neutral-200 p-4 dark:border-neutral-800";
const input="rounded-xl border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-violet-500 dark:border-neutral-700 dark:bg-neutral-950";
function n(v:unknown){return Number(v||0);}
function pct(v:unknown){return `${(n(v)*100).toFixed(1)}%`;}
function money(v:unknown,currency:string){try{return new Intl.NumberFormat(undefined,{style:"currency",currency:currency||"USD",maximumFractionDigits:2}).format(n(v));}catch{return `${currency||"USD"} ${n(v).toFixed(2)}`;}}
function num(v:unknown){return new Intl.NumberFormat().format(Math.round(n(v)));}
function shortId(v:string){return v?`${v.slice(0,8)}…`:"—";}
function creativeName(c:PaidCreativeAnalytics,index:number){return c.snippetLabel?`${c.snippetLabel} · ${c.backgroundName||`Creative ${index+1}`}`:`Creative ${index+1} · ${c.backgroundName||shortId(c.id)}`;}

export default function AdCampaignAnalytics({ad,onMessage}:{ad:AdCampaign;onMessage:(value:string)=>void}){
  const [data,setData]=useState<PaidAdAnalytics|null>(null); const [busy,setBusy]=useState(false);
  const today=useMemo(()=>new Date().toISOString().slice(0,10),[]); const defaultSince=useMemo(()=>ad.metaPublishedAt?String(ad.metaPublishedAt).slice(0,10):new Date(Date.now()-29*86400000).toISOString().slice(0,10),[ad.metaPublishedAt]);
  const [since,setSince]=useState(defaultSince); const [until,setUntil]=useState(today);
  async function load(refresh=false){setBusy(true);try{const out=await promotionApi.paidAnalytics(ad.id,{since,until,refresh});setData(out);if(refresh)onMessage("Meta Insights refreshed. YSong attribution is live.");}catch(e){onMessage(e instanceof Error?e.message:"Could not load paid-ad analytics.");}finally{setBusy(false);}}
  useEffect(()=>{void load(false);},[ad.id]); // eslint-disable-line react-hooks/exhaustive-deps

  const meta=data?.meta.summary||{}; const y=data?.ysong.totals; const d=data?.derived; const currency=d?.currency||ad.currency||"USD";
  const funnel=[
    ["Impressions",n(meta.impressions)],
    ["Meta outbound clicks",n(meta.outboundClicks||meta.linkClicks)],
    ["YSong Smart Link visits",n(y?.views)],
    ["Platform clicks",n(y?.clicks)],
    ["Fan emails",n(y?.emailCaptures)],
  ] as const;
  const maxDaily=Math.max(1,...(data?.meta.daily||[]).map(x=>n(x.outboundClicks||x.linkClicks)));

  if(!ad.metaCampaignId&&!data?.ysong.totals.views)return <div className="mt-5 rounded-2xl border border-dashed border-neutral-300 p-10 text-center dark:border-neutral-700"><div className="text-lg font-semibold">No paid traffic yet</div><p className="mt-2 text-sm text-neutral-500">Publish this campaign to Meta first. Once tagged traffic reaches the YSong Smart Link, this screen joins Meta spend/impressions with YSong destination clicks.</p></div>;

  return <div className="mt-5 space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-lg font-semibold">Paid campaign analytics</h3><p className="text-xs text-neutral-500">Meta delivery metrics + YSong Smart Link behavior. Meta is cached for 10 minutes unless you force a refresh.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-[10px] uppercase tracking-widest text-neutral-500">From<input className={`${input} mt-1 block`} type="date" value={since} onChange={e=>setSince(e.target.value)}/></label><label className="text-[10px] uppercase tracking-widest text-neutral-500">To<input className={`${input} mt-1 block`} type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label><button disabled={busy} onClick={()=>void load(false)} className="rounded-xl border border-neutral-300 px-3 py-2 text-sm disabled:opacity-40 dark:border-neutral-700">Apply</button><button disabled={busy||!ad.metaCampaignId} onClick={()=>void load(true)} className="rounded-xl bg-violet-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40">{busy?"Refreshing…":"Refresh Meta"}</button></div></div>

    {data?.warnings.length?<div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-700 dark:text-amber-300">{data.warnings.map((w,i)=><div key={`${w.code}-${i}`}>{w.message}</div>)}</div>:null}
    {data?.stale&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-700 dark:text-amber-300">Meta refresh failed, so YSong is showing the last cached Meta snapshot. Smart Link activity below is still current.</div>}

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      {[["Spend",money(d?.spend,currency)],["Impressions",num(meta.impressions)],["Reach",num(meta.reach)],["Meta outbound",num(meta.outboundClicks||meta.linkClicks)],["Smart Link visits",num(y?.views)],["Platform clicks",num(y?.clicks)],["Meta CTR",`${n(meta.ctr).toFixed(2)}%`],["Cost / platform click",money(d?.costPerPlatformClick,currency)]].map(([label,value])=><div key={String(label)} className={panel}><div className="text-[10px] uppercase tracking-wider text-neutral-500">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>)}
    </div>

    <div className={panel}><div className="flex items-center justify-between gap-3"><div><div className="font-semibold">Attribution funnel</div><div className="text-xs text-neutral-500">The Meta → YSong boundary is measured, not guessed.</div></div><div className="text-xs text-neutral-500">{data?.capturedAt?`Meta snapshot ${new Date(data.capturedAt).toLocaleString()}`:"YSong-only data"}</div></div><div className="mt-4 grid gap-2 lg:grid-cols-5">{funnel.map(([label,value],i)=><div key={label} className="rounded-xl bg-neutral-100 p-3 dark:bg-neutral-950"><div className="text-[10px] uppercase text-neutral-500">{label}</div><div className="mt-1 text-xl font-semibold">{num(value)}</div>{i>0&&<div className="mt-1 text-[11px] text-neutral-500">{funnel[i-1][1]>0?pct(value/funnel[i-1][1]):"—"} from prior step</div>}</div>)}</div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-4"><div>Smart Link engagement <b>{pct(d?.smartLinkEngagement)}</b></div><div>Meta click → Smart Link <b>{pct(d?.metaToSmartLinkRate)}</b></div><div>Cost / Smart Link visit <b>{money(d?.costPerSmartLinkVisit,currency)}</b></div><div>Meta CPC <b>{money(meta.cpc,currency)}</b></div></div></div>

    <div className="grid gap-5 xl:grid-cols-2">
      <div className={panel}><div className="flex items-center justify-between"><div><div className="font-semibold">Streaming / destination choices</div><div className="text-xs text-neutral-500">What fans chose after the ad click.</div></div>{d?.bestDestination&&<span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] text-emerald-600">Top destination</span>}</div><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-neutral-500"><tr><th className="py-2">Destination</th><th className="py-2 text-right">Clicks</th><th className="py-2 text-right">Share</th><th className="py-2 text-right">Cost/click</th></tr></thead><tbody>{(d?.destinations||[]).map(row=><tr key={row.id} className="border-t border-neutral-100 dark:border-neutral-800"><td className="py-2"><div className="font-medium">{row.label}</div><div className="text-[10px] text-neutral-500">{row.platform}</div></td><td className="py-2 text-right">{num(row.clicks)}</td><td className="py-2 text-right">{pct(row.shareOfPlatformClicks)}</td><td className="py-2 text-right">{money(row.costPerClick,currency)}</td></tr>)}</tbody></table>{!(d?.destinations||[]).length&&<div className="py-8 text-center text-xs text-neutral-500">No attributed platform clicks yet.</div>}</div></div>
      <div className={panel}><div className="font-semibold">Video watch depth</div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3"><div className="rounded-lg bg-neutral-100 p-3 dark:bg-neutral-950"><div className="text-[10px] text-neutral-500">Plays</div><div className="text-lg font-semibold">{num(meta.videoPlays)}</div></div>{[["25%",meta.video25],["50%",meta.video50],["75%",meta.video75],["100%",meta.video100],["ThruPlay",meta.thruPlays]].map(([k,v])=><div key={String(k)} className="rounded-lg bg-neutral-100 p-3 dark:bg-neutral-950"><div className="text-[10px] text-neutral-500">{k}</div><div className="text-lg font-semibold">{num(v)}</div></div>)}</div><p className="mt-3 text-[11px] text-neutral-500">Video metrics are shown when Meta exposes them for the campaign/account. Missing fields do not block the rest of the report.</p></div>
    </div>

    <div className={panel}><div className="flex items-center justify-between"><div><div className="font-semibold">Creative leaderboard</div><div className="text-xs text-neutral-500">Connects each rendered audio-snippet/background combination to its Meta Ad and downstream Smart Link behavior.</div></div>{d?.bestCreative&&<span className="rounded-full bg-violet-500/10 px-2 py-1 text-[10px] text-violet-500">Current winner: {d.bestCreative.snippetLabel||shortId(d.bestCreative.id)}</span>}</div><div className="mt-3 overflow-x-auto"><table className="min-w-[900px] w-full text-left text-xs"><thead className="text-neutral-500"><tr><th className="py-2">Creative</th><th className="text-right">Spend</th><th className="text-right">Impressions</th><th className="text-right">Meta outbound</th><th className="text-right">Smart visits</th><th className="text-right">Platform clicks</th><th className="text-right">Engagement</th><th className="text-right">Cost/platform click</th></tr></thead><tbody>{(d?.creatives||[]).map((c,i)=><tr key={c.id} className="border-t border-neutral-100 dark:border-neutral-800"><td className="py-2 pr-4"><div className="font-medium">{creativeName(c,i)}</div><div className="text-[10px] text-neutral-500">{c.snippetStartSeconds.toFixed(1)}s–{(c.snippetStartSeconds+c.snippetDurationSeconds).toFixed(1)}s · {shortId(c.id)}</div></td><td className="text-right">{money(c.meta.spend,currency)}</td><td className="text-right">{num(c.meta.impressions)}</td><td className="text-right">{num(c.meta.outboundClicks||c.meta.linkClicks)}</td><td className="text-right">{num(c.ysong.views)}</td><td className="text-right">{num(c.ysong.clicks)}</td><td className="text-right">{pct(c.derived.smartLinkEngagement)}</td><td className="text-right">{money(c.derived.costPerPlatformClick,currency)}</td></tr>)}</tbody></table></div></div>

    <div className="grid gap-5 xl:grid-cols-2">
      <div className={panel}><div className="font-semibold">Placement performance</div><div className="mt-3 overflow-x-auto"><table className="w-full text-xs"><thead className="text-neutral-500"><tr><th className="py-2 text-left">Placement</th><th className="text-right">Impressions</th><th className="text-right">Outbound</th><th className="text-right">Spend</th></tr></thead><tbody>{(data?.meta.placements||[]).map((r,i)=><tr key={`${r.publisherPlatform}-${r.platformPosition}-${i}`} className="border-t border-neutral-100 dark:border-neutral-800"><td className="py-2">{r.publisherPlatform||"Meta"} · {r.platformPosition||"unknown"}</td><td className="text-right">{num(r.impressions)}</td><td className="text-right">{num(r.outboundClicks||r.linkClicks)}</td><td className="text-right">{money(r.spend,currency)}</td></tr>)}</tbody></table>{!(data?.meta.placements||[]).length&&<div className="py-6 text-center text-xs text-neutral-500">No placement breakdown available yet.</div>}</div></div>
      <div className={panel}><div className="font-semibold">Country performance</div><div className="mt-3 max-h-72 overflow-auto"><table className="w-full text-xs"><thead className="sticky top-0 bg-white text-neutral-500 dark:bg-neutral-900"><tr><th className="py-2 text-left">Country</th><th className="text-right">Reach</th><th className="text-right">Outbound</th><th className="text-right">Spend</th></tr></thead><tbody>{(data?.meta.countries||[]).sort((a,b)=>n(b.outboundClicks||b.linkClicks)-n(a.outboundClicks||a.linkClicks)).map((r,i)=><tr key={`${r.country}-${i}`} className="border-t border-neutral-100 dark:border-neutral-800"><td className="py-2">{r.country||"—"}</td><td className="text-right">{num(r.reach)}</td><td className="text-right">{num(r.outboundClicks||r.linkClicks)}</td><td className="text-right">{money(r.spend,currency)}</td></tr>)}</tbody></table>{!(data?.meta.countries||[]).length&&<div className="py-6 text-center text-xs text-neutral-500">No country breakdown available yet.</div>}</div></div>
    </div>

    <div className={panel}><div className="font-semibold">Daily Meta outbound clicks</div><div className="mt-4 flex min-h-28 items-end gap-1 overflow-x-auto">{(data?.meta.daily||[]).map((r,i)=>{const value=n(r.outboundClicks||r.linkClicks);const h=Math.max(2,Math.round((value/maxDaily)*100));return <div key={`${r.dateStart}-${i}`} className="flex min-w-8 flex-1 flex-col items-center justify-end gap-1"><div title={`${r.dateStart}: ${value}`} className="w-full rounded-t bg-violet-500/70" style={{height:`${h}px`}}/><div className="text-[9px] text-neutral-500">{String(r.dateStart||"").slice(5)}</div></div>;})}{!(data?.meta.daily||[]).length&&<div className="w-full py-8 text-center text-xs text-neutral-500">Daily Meta data will appear after delivery begins.</div>}</div></div>
  </div>;
}
