import { useMemo } from "react";
import type { AdsAssistantContext, AdsAssistantResponse } from "./adsSmartAssistantContract";
import { validateAdsAssistantResponse } from "./adsSmartAssistantContract";

export type AdsStudioSelection = { kind: "audio" | "visual" | "text"; trackId: string; clipId: string; label: string; startSeconds: number; durationSeconds: number; text?: string } | null;

function responseFor(context: AdsAssistantContext, selection: AdsStudioSelection): AdsAssistantResponse {
  const suggestions: AdsAssistantResponse["suggestions"] = [];
  if (selection) {
    suggestions.push({ kind: "creative", title: selection.kind === "text" ? "Review this overlay in the mobile preview" : "Review this selected timeline range", rationale: selection.kind === "text" ? `The selected overlay “${selection.text || selection.label}” runs from ${selection.startSeconds.toFixed(1)}s for ${selection.durationSeconds.toFixed(1)}s. Check that it stays readable against the visual.` : `The selected ${selection.kind} clip “${selection.label}” runs from ${selection.startSeconds.toFixed(1)}s for ${selection.durationSeconds.toFixed(1)}s. Check its timing against the hook and opening.`, evidencePaths: ["evidence.audio.trackId"], confidence: "medium" });
  }
  if (context.unavailable.includes("genre_analysis")) suggestions.push({ kind: "creative", title: "Add music analysis for more tailored ideas", rationale: "No Audio Intelligence result is available in this session, so music-fit guidance would be an inference.", evidencePaths: ["evidence.genre.campaignGenre"], confidence: "low" });
  if (context.evidence.creative.selected.length && !context.evidence.creative.selected.some(item => item.studio)) suggestions.push({ kind: "creative", title: "Open the saved Studio timeline", rationale: "The selected creative has no loaded timeline in this context yet; timeline-specific guidance is unavailable.", evidencePaths: [], confidence: "low" });
  if (context.evidence.destination.enabled.length === 0) suggestions.push({ kind: "destination", title: "Review Smart Link destinations", rationale: "No enabled listening destinations are present in the selected Smart Link snapshot.", evidencePaths: ["evidence.destination.smartLinkId"], confidence: "medium" });
  if (context.evidence.analytics?.stale) suggestions.push({ kind: "measurement", title: "Refresh campaign evidence", rationale: "The available analytics snapshot is marked stale; treat performance comparisons as provisional.", evidencePaths: ["evidence.analytics.stale"], confidence: "high" });
  const value: AdsAssistantResponse = { schemaVersion: 1, summary: selection ? `Focused on ${selection.kind === "text" ? "the selected overlay" : `the selected ${selection.kind} range`} in ${context.evidence.release.title}. Guidance uses the current campaign and creative snapshot.` : `Reviewing ${context.evidence.release.title} for ${context.evidence.campaign.goal.replaceAll("_", " ")}. Suggestions are advisory and grounded in the current Ads snapshot.`, suggestions: suggestions.slice(0, 8) };
  validateAdsAssistantResponse(value, context);
  return value;
}

export default function AdsSmartAssistantPanel({ context, selection, onNavigate }: { context: AdsAssistantContext | null; selection: AdsStudioSelection; onNavigate: (step: "audio" | "generate" | "setup" | "intelligence") => void }) {
  const response = useMemo(() => context ? responseFor(context, selection) : null, [context, selection]);
  if (!context || !response) return <section aria-label="Ads Smart Assistant" className="rounded-2xl border border-dashed border-neutral-300 p-4 text-sm text-neutral-500 dark:border-neutral-700"><div className="font-semibold text-neutral-700 dark:text-neutral-200">Ads Smart Assistant</div><p className="mt-1">Choose an Ads campaign with its verified track and Smart Link to get context-aware guidance.</p></section>;
  return <section aria-label="Ads Smart Assistant" className="rounded-2xl border border-violet-500/25 bg-violet-500/[0.035] p-4 dark:bg-violet-500/[0.04]">
    <div className="flex items-center justify-between gap-2"><div><div className="text-[10px] uppercase tracking-[.18em] text-violet-500">Ads Smart Assistant</div><h3 className="mt-1 font-semibold">Current selection</h3></div><span className="rounded-full border border-violet-500/25 px-2 py-1 text-[10px] text-violet-600 dark:text-violet-300">Advisory</span></div>
    {selection && <div className="mt-3 rounded-xl border border-violet-500/20 bg-white/60 p-3 text-xs dark:bg-neutral-950/40"><div className="font-medium">{selection.kind === "text" ? "Overlay" : `${selection.kind} range`}: {selection.label}</div><div className="mt-1 text-neutral-500">{selection.startSeconds.toFixed(1)}s–{(selection.startSeconds + selection.durationSeconds).toFixed(1)}s{selection.text ? ` · “${selection.text}”` : ""}</div></div>}
    <p className="mt-3 text-sm text-neutral-700 dark:text-neutral-300">{response.summary}</p>
    {response.suggestions.length > 0 ? <div className="mt-3 space-y-2">{response.suggestions.map((item, index) => <article key={`${item.kind}:${index}`} className="rounded-xl border border-neutral-200 bg-white/70 p-3 dark:border-neutral-800 dark:bg-neutral-950/35"><div className="flex items-center justify-between gap-2"><h4 className="text-sm font-medium">{item.title}</h4><span className="text-[10px] text-neutral-500">{item.confidence} confidence</span></div><p className="mt-1 text-xs leading-5 text-neutral-600 dark:text-neutral-400">{item.rationale}</p><div className="mt-2 flex flex-wrap items-center gap-2"><span className="text-[10px] text-neutral-400">{item.evidencePaths.length ? `Evidence: ${item.evidencePaths.join(", ")}` : "Inference · limited evidence"}</span>{item.kind === "measurement" && <button type="button" onClick={() => onNavigate("intelligence")} className="ml-auto rounded-lg border px-2.5 py-1.5 text-xs">Review evidence</button>}{item.kind === "destination" && <button type="button" onClick={() => onNavigate("setup")} className="ml-auto rounded-lg border px-2.5 py-1.5 text-xs">Review setup</button>}</div></article>)}</div> : <div className="mt-3 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3 text-xs">No immediate concerns surfaced in this snapshot. You can keep editing and ask for another review.</div>}
    <p className="mt-3 text-[10px] text-neutral-500">Suggestions are structured and advisory. Review any change in the existing Ads workflow; nothing is applied or published here.</p>
  </section>;
}
