import { useEffect, useMemo, useState } from "react";
import AdCampaignStudio from "./AdCampaignStudio";
import { promotionApi, publicPromotionUrl, type MetaConnection, type PromotionAnalytics, type PromotionCampaign, type PromotionCatalog, type PromotionDestination, type PromotionHealth, type PromotionRelease } from "./api";

type Mode="campaigns"|"create"|"ads"|"meta";
const emptyDestination=():PromotionDestination=>({platform:"",label:"",url:"",kind:"stream",enabled:true});
const inputClass="w-full rounded-xl border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-violet-500 dark:border-neutral-700 dark:bg-neutral-950";
const panel="rounded-2xl border border-neutral-200 bg-white/80 p-5 dark:border-neutral-800 dark:bg-neutral-900/55";
function pct(v:number){return `${Math.round((Number(v)||0)*1000)/10}%`;}
function fmtDate(v:string|null|undefined){if(!v)return "";try{return new Date(v).toLocaleDateString();}catch{return "";}}

export default function PromotionCenterApp({onBack}:{onBack:()=>void}){
  const [mode,setMode]=useState<Mode>("campaigns"); const [health,setHealth]=useState<PromotionHealth|null>(null); const [catalog,setCatalog]=useState<PromotionCatalog|null>(null); const [releases,setReleases]=useState<PromotionRelease[]>([]); const [campaigns,setCampaigns]=useState<PromotionCampaign[]>([]);
  const [selected,setSelected]=useState<PromotionCampaign|null>(null); const [analytics,setAnalytics]=useState<PromotionAnalytics|null>(null); const [fans,setFans]=useState<Array<{email:string;source:string;provider:string;createdAt:string}>>([]); const [metaConnections,setMetaConnections]=useState<MetaConnection[]>([]);
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const [form,setForm]=useState({sourceReleaseId:"",kind:"smart_link" as PromotionCampaign["kind"],title:"",artistName:"",description:"",genre:"",releaseDate:"",slug:"",headline:"",ctaLabel:"",accentColor:"#8b5cf6",seoQuery:""});
  const [destinations,setDestinations]=useState<PromotionDestination[]>([emptyDestination()]);

  async function load(){ try{const [h,k,r,c,m]=await Promise.all([promotionApi.health(),promotionApi.catalog(),promotionApi.releases(),promotionApi.campaigns(),promotionApi.metaStatus()]);setHealth(h);setCatalog(k);setReleases(r.releases);setCampaigns(c.campaigns);setMetaConnections(m.connections);}catch(e){setMessage(e instanceof Error?e.message:"Promotion Center could not load.");} }
  useEffect(()=>{void load();},[]);
  useEffect(()=>{ const handler=(event:MessageEvent)=>{ if(event.data?.type!=="ysong-meta-oauth")return; setMessage(event.data.ok?"Meta Business connection completed.":String(event.data.message||"Meta connection failed.")); void load(); }; window.addEventListener("message",handler); return()=>window.removeEventListener("message",handler); },[]);

  function chooseRelease(id:string){ const r=releases.find(x=>x.id===id); setForm(f=>({...f,sourceReleaseId:id,title:r?.title||f.title,artistName:r?.artistName||f.artistName,genre:r?.genre||f.genre,seoQuery:r?`${r.artistName} ${r.title} ${r.genre}`.trim():f.seoQuery})); }
  async function create(){ setBusy(true);setMessage("");try{const payload={...form,sourceReleaseId:form.sourceReleaseId||null,releaseDate:form.releaseDate||null,destinations:destinations.filter(d=>d.label.trim()&&d.url.trim())};const out=await promotionApi.create(payload);setCampaigns(c=>[out.campaign,...c]);setSelected(out.campaign);setMode("campaigns");await openCampaign(out.campaign.id);setMessage("Campaign created as a draft. Nothing is public until you publish it.");}catch(e){setMessage(e instanceof Error?e.message:"Campaign creation failed.");}finally{setBusy(false);} }
  async function openCampaign(id:string){ setBusy(true);try{const [detail,leadData]=await Promise.all([promotionApi.campaign(id),promotionApi.fans(id)]);setSelected(detail.campaign);setAnalytics(detail.analytics);setFans(leadData.fans);setCampaigns(c=>c.map(x=>x.id===id?detail.campaign:x));}catch(e){setMessage(e instanceof Error?e.message:"Campaign load failed.");}finally{setBusy(false);} }
  async function setStatus(status:PromotionCampaign["status"]){ if(!selected)return;setBusy(true);try{const out=await promotionApi.status(selected.id,status);setSelected(out.campaign);setCampaigns(c=>c.map(x=>x.id===out.campaign.id?out.campaign:x));setMessage(status==="active"?"Campaign is live.":`Campaign moved to ${status}.`);}catch(e){setMessage(e instanceof Error?e.message:"Status update failed.");}finally{setBusy(false);} }
  async function refreshSeo(){ if(!selected)return;setBusy(true);try{await promotionApi.refreshSeo(selected.id,selected.seoQuery);await openCampaign(selected.id);setMessage("SEO Intelligence snapshot refreshed using the existing YSong SEO engine.");}catch(e){setMessage(e instanceof Error?e.message:"SEO refresh failed.");}finally{setBusy(false);} }
  async function connectMeta(){ setBusy(true);try{const {url}=await promotionApi.metaStart();const popup=window.open(url,"ysong_meta_oauth","popup,width=720,height=820");if(!popup) window.location.href=url;else popup.focus();}catch(e){setMessage(e instanceof Error?e.message:"Meta connection could not start.");}finally{setBusy(false);} }
  async function metaPublish(channel:"facebook"|"instagram"){if(!selected)return;const defaultText=`${selected.artistName ? `${selected.artistName} — ` : ""}${selected.title}\n${selected.publicUrl}`;setBusy(true);try{await promotionApi.metaPublish(selected.id,channel,defaultText);setMessage(`Published to ${channel === "facebook" ? "Facebook" : "Instagram"} through the connected Meta business property.`);}catch(e){setMessage(e instanceof Error?e.message:"Meta publishing failed.");}finally{setBusy(false);} }
  function exportFans(){ if(!selected)return;const rows=[["email","source","provider","created_at"],...fans.map(f=>[f.email,f.source,f.provider,f.createdAt])];const csv=rows.map(r=>r.map(v=>`"${String(v||"").replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download=`${selected.slug}-fans.csv`;a.click();URL.revokeObjectURL(url);}
  const activeMeta=metaConnections.find(x=>x.active)||null;
  const visibleCampaigns=useMemo(()=>campaigns.filter(c=>c.status!=="archived"),[campaigns]);

  return <div className="h-full min-h-0 overflow-y-auto bg-neutral-50 text-neutral-900 dark:bg-neutral-950 dark:text-neutral-100">
    <div className="mx-auto max-w-7xl px-5 py-6 md:px-8">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><button onClick={onBack} className="text-xs text-violet-500 hover:text-violet-400">← Tools</button><div className="mt-2 text-[11px] uppercase tracking-[.24em] text-violet-500">Phase 23</div><h1 className="!mt-1 !text-3xl !font-semibold">Promotion Center</h1><p className="mt-1 max-w-3xl text-sm text-neutral-500">Smart Links, release funnels, fan capture, paid-ad creative generation, campaign attribution, SEO Intelligence, and Meta Business connectivity. Artist data stays owned by YSong.</p></div>
        <div className="flex gap-2">{(["campaigns","create","ads","meta"] as Mode[]).map(x=><button key={x} onClick={()=>setMode(x)} className={`rounded-xl px-3 py-2 text-xs font-medium ${mode===x?"bg-violet-600 text-white":"border border-neutral-300 dark:border-neutral-700"}`}>{x==="campaigns"?"Smart Links":x==="create"?"+ New Smart Link":x==="ads"?"Ad Campaigns":"Meta Business"}</button>)}</div></div>
      {message&&<div className="mt-4 rounded-xl border border-violet-500/25 bg-violet-500/10 px-4 py-3 text-sm text-violet-700 dark:text-violet-200">{message}</div>}
      <datalist id="promotion-platforms">{catalog?.platforms.map(platform=><option key={platform.id} value={platform.label}/>)}</datalist>

      {mode==="ads"&&<AdCampaignStudio campaigns={campaigns} releases={releases} health={health} onMessage={setMessage}/>}

      {mode==="create"&&<div className="mt-6 grid gap-5 lg:grid-cols-[1fr_.9fr]">
        <div className={panel}><h2 className="text-lg font-semibold">Campaign identity</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">
          <label className="text-xs text-neutral-500 sm:col-span-2">Import a YSong release<select className={inputClass} value={form.sourceReleaseId} onChange={e=>chooseRelease(e.target.value)}><option value="">Manual campaign</option>{releases.map(r=><option key={r.id} value={r.id}>{r.artistName} — {r.title}</option>)}</select></label>
          <label className="text-xs text-neutral-500">Campaign type<select className={inputClass} value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as PromotionCampaign["kind"]})}><option value="smart_link">Smart Link</option><option value="presave">Pre-save</option><option value="release">Release landing page</option></select></label>
          <label className="text-xs text-neutral-500">Release date<input className={inputClass} type="date" value={form.releaseDate} onChange={e=>setForm({...form,releaseDate:e.target.value})}/></label>
          <label className="text-xs text-neutral-500">Artist<input className={inputClass} value={form.artistName} onChange={e=>setForm({...form,artistName:e.target.value})}/></label><label className="text-xs text-neutral-500">Title<input className={inputClass} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
          <label className="text-xs text-neutral-500">Genre<input className={inputClass} value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}/></label><label className="text-xs text-neutral-500">URL slug<input className={inputClass} placeholder="auto-generated if blank" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label>
          <label className="text-xs text-neutral-500 sm:col-span-2">Headline<input className={inputClass} value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})}/></label><label className="text-xs text-neutral-500 sm:col-span-2">Description<textarea className={`${inputClass} min-h-24`} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
          <label className="text-xs text-neutral-500 sm:col-span-2">SEO Intelligence query<input className={inputClass} value={form.seoQuery} onChange={e=>setForm({...form,seoQuery:e.target.value})}/></label>
        </div></div>
        <div className={panel}><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Destinations</h2><p className="text-xs text-neutral-500">Streaming, store, social, or pre-save destinations.</p></div><button onClick={()=>setDestinations(d=>[...d,emptyDestination()])} className="rounded-lg border border-neutral-300 px-3 py-1.5 text-xs dark:border-neutral-700">+ Link</button></div><div className="mt-4 space-y-3">{destinations.map((d,i)=><div key={i} className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><div className="grid gap-2 sm:grid-cols-2"><input className={inputClass} list="promotion-platforms" placeholder="Platform (Spotify, FLO, Rumble, custom…)" value={d.platform} onChange={e=>setDestinations(v=>v.map((x,n)=>n===i?{...x,platform:e.target.value}:x))}/><select className={inputClass} value={d.kind} onChange={e=>setDestinations(v=>v.map((x,n)=>n===i?{...x,kind:e.target.value as PromotionDestination["kind"]}:x))}><option value="stream">Stream</option><option value="presave">Pre-save</option><option value="store">Store</option><option value="social">Social</option><option value="other">Other</option></select><input className={inputClass} placeholder="Button label" value={d.label} onChange={e=>setDestinations(v=>v.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><input className={inputClass} placeholder="https://..." value={d.url} onChange={e=>setDestinations(v=>v.map((x,n)=>n===i?{...x,url:e.target.value}:x))}/></div>{destinations.length>1&&<button onClick={()=>setDestinations(v=>v.filter((_,n)=>n!==i))} className="mt-2 text-xs text-red-500">Remove</button>}</div>)}</div><button disabled={busy||!form.title.trim()} onClick={()=>void create()} className="mt-5 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Create draft campaign</button></div>
      </div>}

      {mode==="meta"&&<div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className={panel}><div className="text-xs uppercase tracking-widest text-violet-500">Meta Graph {health?.meta.graphVersion||""}</div><h2 className="mt-2 text-xl font-semibold">Meta Business Suite connection</h2><p className="mt-2 text-sm text-neutral-500">YSong connects the Facebook Page and its linked Instagram professional account through Meta Graph API. Tokens stay encrypted on the server.</p><div className="mt-4 rounded-xl border border-neutral-200 p-3 text-xs dark:border-neutral-800"><div>App configured: <b>{health?.meta.configured?"Yes":"No"}</b></div><div className="mt-1">Public HTTPS ready: <b>{health?.public.productionReady?"Yes":"Local/dev"}</b></div></div><button disabled={busy||!health?.meta.configured} onClick={()=>void connectMeta()} className="mt-4 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Connect Facebook + Instagram</button>{!health?.meta.configured&&<p className="mt-2 text-xs text-amber-500">Server needs META_APP_ID, META_APP_SECRET, and META_TOKEN_ENCRYPTION_KEY.</p>}</div>
        <div className={panel}><h2 className="text-lg font-semibold">Managed Pages</h2><div className="mt-3 space-y-2">{metaConnections.length===0?<p className="text-sm text-neutral-500">No Meta properties connected yet.</p>:metaConnections.map(c=><div key={c.id} className={`rounded-xl border p-3 ${c.active?"border-blue-500/50 bg-blue-500/5":"border-neutral-200 dark:border-neutral-800"}`}><div className="flex items-start justify-between gap-3"><div><div className="font-medium">{c.pageName}</div><div className="text-xs text-neutral-500">Facebook Page · {c.pageId}</div><div className="mt-1 text-xs text-neutral-500">Instagram: {c.instagramUsername?`@${c.instagramUsername}`:"No linked professional account"}</div></div><div className="flex gap-2">{!c.active&&<button onClick={async()=>{await promotionApi.metaSelect(c.id);await load();}} className="rounded-lg border px-2 py-1 text-xs dark:border-neutral-700">Use</button>}<button onClick={async()=>{await promotionApi.metaDisconnect(c.id);await load();}} className="text-xs text-red-500">Disconnect</button></div></div></div>)}</div></div>
      </div>}

      {mode==="campaigns"&&<div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className={panel}><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Campaigns</h2><span className="text-xs text-neutral-500">{visibleCampaigns.length}</span></div><div className="mt-3 space-y-2">{visibleCampaigns.length===0?<p className="text-sm text-neutral-500">No campaigns yet. Create one only when you want it.</p>:visibleCampaigns.map(c=><button key={c.id} onClick={()=>void openCampaign(c.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id===c.id?"border-violet-500/60 bg-violet-500/5":"border-neutral-200 dark:border-neutral-800"}`}><div className="flex items-center justify-between gap-2"><span className="font-medium">{c.title}</span><span className={`rounded-full px-2 py-0.5 text-[10px] uppercase ${c.status==="active"?"bg-emerald-500/10 text-emerald-500":"bg-neutral-500/10 text-neutral-500"}`}>{c.status}</span></div><div className="mt-1 text-xs text-neutral-500">{c.artistName||"Unknown artist"} · {c.kind.replace("_"," ")}</div></button>)}</div></div>
        <div className={panel}>{!selected?<div className="grid min-h-80 place-items-center text-sm text-neutral-500">Select a campaign to inspect its funnel.</div>:<div><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs uppercase tracking-widest text-violet-500">{selected.kind.replace("_"," ")}</div><h2 className="mt-1 text-2xl font-semibold">{selected.title}</h2><div className="text-sm text-neutral-500">{selected.artistName} {selected.genre?`· ${selected.genre}`:""} {selected.releaseDate?`· ${fmtDate(selected.releaseDate)}`:""}</div></div><div className="flex gap-2">{selected.status!=="active"?<button disabled={busy} onClick={()=>void setStatus("active")} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Publish</button>:<button disabled={busy} onClick={()=>void setStatus("draft")} className="rounded-xl border px-3 py-2 text-xs dark:border-neutral-700">Unpublish</button>}</div></div>
          {selected.status==="active"&&<div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><div className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><div className="text-[10px] uppercase tracking-widest text-neutral-500">Campaign URL</div><div className="mt-1 break-all text-sm">{selected.publicUrl}</div><button onClick={()=>void navigator.clipboard.writeText(selected.publicUrl)} className="mt-2 text-xs text-violet-500">Copy link</button></div><img className="h-28 w-28 rounded-lg border bg-white p-1" src={publicPromotionUrl(`/api/promotion/public/${encodeURIComponent(selected.slug)}/qr.svg`)} alt="Campaign QR code"/></div>}
          <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Views",analytics?.totals.views||0],["Outbound",analytics?.totals.clicks||0],["Emails",analytics?.totals.emailCaptures||0],["Confirmed",analytics?.totals.conversions||0]].map(([k,v])=><div key={String(k)} className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><div className="text-[10px] uppercase text-neutral-500">{k}</div><div className="mt-1 text-xl font-semibold">{v}</div></div>)}</div>
          <div className="mt-2 grid gap-2 text-xs sm:grid-cols-3"><div>Click rate <b>{pct(analytics?.totals.clickRate||0)}</b></div><div>Email capture <b>{pct(analytics?.totals.emailRate||0)}</b></div><div>Confirmed conversion <b>{pct(analytics?.totals.conversionRate||0)}</b></div></div>
          <div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="flex items-center justify-between"><div><div className="font-medium">SEO Intelligence</div><div className="text-xs text-neutral-500">Uses YSong's existing SEO engine, not a duplicate.</div></div><button disabled={busy} onClick={()=>void refreshSeo()} className="rounded-lg border px-2 py-1 text-xs dark:border-neutral-700">Refresh</button></div><div className="mt-3 text-xs text-neutral-500">Query: {selected.seoQuery||"Not set"}</div><div className="mt-1 text-xs">Snapshot: {Object.keys(selected.seoSnapshot||{}).length?"Available":"Not analyzed yet"}</div></div>
            <div className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="font-medium">Meta Business</div><div className="mt-1 text-xs text-neutral-500">{activeMeta?`${activeMeta.pageName}${activeMeta.instagramUsername?` + @${activeMeta.instagramUsername}`:""}`:"No active Meta Page"}</div><div className="mt-3 flex gap-2"><button disabled={busy||!activeMeta||selected.status!=="active"} onClick={()=>void metaPublish("facebook")} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Publish Facebook</button><button disabled={busy||!activeMeta?.instagramUserId||selected.status!=="active"||!selected.hasArtwork} onClick={()=>void metaPublish("instagram")} className="rounded-lg bg-fuchsia-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Publish Instagram</button></div></div></div>
          <div className="mt-5 rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="flex items-center justify-between"><div><div className="font-medium">Fan email capture</div><div className="text-xs text-neutral-500">Consent is required on the public landing page.</div></div><button disabled={!fans.length} onClick={exportFans} className="rounded-lg border px-2 py-1 text-xs disabled:opacity-40 dark:border-neutral-700">Export CSV</button></div>{fans.length?<div className="mt-3 max-h-36 overflow-auto text-xs">{fans.slice(0,12).map(f=><div key={`${f.email}-${f.createdAt}`} className="flex justify-between border-t border-neutral-100 py-2 dark:border-neutral-800"><span>{f.email}</span><span className="text-neutral-500">{fmtDate(f.createdAt)}</span></div>)}</div>:<div className="mt-3 text-xs text-neutral-500">No fan emails yet.</div>}</div>
          <div className="mt-5"><div className="font-medium">Destinations</div><div className="mt-2 space-y-2">{selected.destinations.map(d=><div key={d.id||d.url} className="flex items-center justify-between rounded-lg border border-neutral-200 px-3 py-2 text-sm dark:border-neutral-800"><span>{d.label}</span><span className="text-xs text-neutral-500">{d.platform} · {d.kind}</span></div>)}</div></div>
        </div>}</div></div>}
    </div>
  </div>;
}
