import { midiOnsets } from "../lib/midiOnsets";
import { useEffect, useRef, useState } from "react";
import { importPlainLyrics, lineText, lyricsToPlainText, makeLine, makeSection, makeSyllables, restoreLyricsVersion, saveLyricsVersion, suggestTiming, suggestMidiTiming, updateLineText, type LyricsDocument, type LyricLine, type LyricWord, type LyricSyllable } from "../lib/lyricsDocument";

type Props = { document: LyricsDocument; onChange: (document: LyricsDocument) => void };
const parse = (value: string) => value.trim() === "" ? null : Math.max(0, Math.round(Number(value) || 0));
const manual = { source: "manual" as const, score: 1 };
const syllablesOf = (word: LyricWord) => word.syllables?.length ? word.syllables : [{ id: `${word.id}:0`, text: word.text, startMs: null, endMs: null }];
function TimeField({ label, value, onChange }: { label: string; value: number | null; onChange: (value: number | null) => void }) {
  return <input type="number" min="0" className="w-20 rounded border border-white/10 bg-black/20 px-1" aria-label={label} placeholder="ms" value={value ?? ""} onChange={(event) => onChange(parse(event.target.value))} />;
}
export default function LyricsWorkspace({ document, onChange }: Props) {
  const audio = useRef<HTMLAudioElement>(null);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [durationMs, setDurationMs] = useState(0);
  const [notes, setNotes] = useState<number[]>([]);
  const [midiError, setMidiError] = useState("");
  const [plainOpen, setPlainOpen] = useState(false);
  const [plain, setPlain] = useState("");
  const [versionLabel, setVersionLabel] = useState("");
  useEffect(() => () => { if (audioUrl) URL.revokeObjectURL(audioUrl); }, [audioUrl]);
  const changeSection = (sectionId: string, update: (section: LyricsDocument["sections"][number]) => LyricsDocument["sections"][number]) => onChange({ ...document, sections: document.sections.map((section) => section.id === sectionId ? update(section) : section) });
  const changeLine = (sectionId: string, lineId: string, update: (line: LyricLine) => LyricLine) => changeSection(sectionId, (section) => ({ ...section, lines: section.lines.map((line) => line.id === lineId ? update(line) : line) }));
  const changeWord = (sectionId: string, lineId: string, wordId: string, update: (word: LyricWord) => LyricWord) => changeLine(sectionId, lineId, (line) => ({ ...line, words: line.words.map((word) => word.id === wordId ? update(word) : word) }));
  const changeSyllable = (sectionId: string, lineId: string, wordId: string, syllableId: string, update: (syllable: LyricSyllable) => LyricSyllable) => changeWord(sectionId, lineId, wordId, (word) => ({ ...word, syllables: syllablesOf(word).map((syllable) => syllable.id === syllableId ? update(syllable) : syllable) }));
  const playhead = () => Math.round((audio.current?.currentTime ?? 0) * 1000);
  return <div className="rounded-xl border border-white/10 bg-white/[.025] p-3 space-y-3 text-xs">
    <div className="flex justify-between"><div><b>Lyrics workspace</b><p className="text-neutral-400">Phrase, word, and syllable timing in milliseconds. Suggestions are approximate and require audio.</p></div><button type="button" onClick={() => { setPlain(lyricsToPlainText(document)); setPlainOpen(!plainOpen); }}>Import / export text</button></div>
    {plainOpen && <div><textarea className="input min-h-36" aria-label="Plain lyrics" value={plain} onChange={(event) => setPlain(event.target.value)} /><button type="button" onClick={() => { onChange(importPlainLyrics(plain, document)); setPlainOpen(false); }}>Import text</button><button type="button" onClick={() => void navigator.clipboard.writeText(lyricsToPlainText(document))}>Copy export</button></div>}
    <div className="rounded border border-white/10 p-2 space-y-2"><label>Audio reference <input type="file" accept="audio/*" onChange={(event) => setAudioUrl(event.target.files?.[0] ? URL.createObjectURL(event.target.files[0]) : null)} /></label>{audioUrl && <audio ref={audio} src={audioUrl} controls className="w-full" onLoadedMetadata={(event) => setDurationMs(Math.round(event.currentTarget.duration * 1000))} />}<label>MIDI note reference <input type="file" accept=".mid,.midi,audio/midi" onChange={(event) => { const file = event.target.files?.[0]; setNotes([]); setMidiError(""); if (file) void file.arrayBuffer().then((buffer) => setNotes(midiOnsets(new Uint8Array(buffer)))).catch((error) => setMidiError(error instanceof Error ? error.message : "Cannot read MIDI")); }} /></label><p className="text-neutral-500">Play or seek the local recording, then tap boundaries. MIDI suggestions use note onsets within the phrase. Files stay on your device.</p>{notes.length > 0 && <p>{notes.length} MIDI onsets loaded</p>}{midiError && <p role="alert">{midiError}</p>}</div>
    {document.sections.map((section) => <div key={section.id} className="rounded border border-white/10 p-2 space-y-2"><div className="flex gap-2"><input className="input" aria-label="Section name" value={section.name} onChange={(event) => changeSection(section.id, (item) => ({ ...item, name: event.target.value }))} /><button type="button" disabled={document.sections.length === 1} onClick={() => onChange({ ...document, sections: document.sections.filter((item) => item.id !== section.id) })}>Remove</button></div>
      {section.lines.map((line) => <div key={line.id} className="border-t border-white/10 pt-2 space-y-2"><div className="flex gap-2"><input className="input" aria-label="Lyric line" value={lineText(line)} onChange={(event) => changeLine(section.id, line.id, (item) => updateLineText(item, event.target.value))} /><button type="button" aria-label="Remove line" onClick={() => changeSection(section.id, (item) => ({ ...item, lines: item.lines.filter((entry) => entry.id !== line.id) }))}>Ãƒâ€”</button></div><div className="flex flex-wrap items-center gap-2"><span>Phrase</span><TimeField label="Phrase start milliseconds" value={line.startMs} onChange={(value) => changeLine(section.id, line.id, (item) => ({ ...item, startMs: value, confidence: manual }))} /><TimeField label="Phrase end milliseconds" value={line.endMs} onChange={(value) => changeLine(section.id, line.id, (item) => ({ ...item, endMs: value, confidence: manual }))} />{audioUrl && <><button type="button" onClick={() => changeLine(section.id, line.id, (item) => ({ ...item, startMs: playhead(), confidence: manual }))}>Tap start</button><button type="button" onClick={() => changeLine(section.id, line.id, (item) => ({ ...item, endMs: playhead(), confidence: manual }))}>Tap end</button><button type="button" disabled={line.startMs == null || line.endMs == null} onClick={() => changeLine(section.id, line.id, (item) => suggestTiming(item, item.startMs!, item.endMs!, "audio"))}>Suggest spacing</button></>}{notes.length > 0 && <button type="button" disabled={line.startMs == null || line.endMs == null} onClick={() => changeLine(section.id, line.id, (item) => suggestMidiTiming(item, notes, item.startMs!, item.endMs!))}>Suggest from MIDI notes</button>}{line.confidence && <span>{line.confidence.source} {Math.round(line.confidence.score * 100)}%</span>}</div>{audioUrl && durationMs > 0 && <div className="flex gap-2"><label className="flex-1">Drag start<input type="range" className="w-full" min="0" max={durationMs} value={line.startMs ?? 0} onChange={(event) => changeLine(section.id, line.id, (item) => ({ ...item, startMs: Number(event.target.value), confidence: manual }))} /></label><label className="flex-1">Drag end<input type="range" className="w-full" min="0" max={durationMs} value={line.endMs ?? 0} onChange={(event) => changeLine(section.id, line.id, (item) => ({ ...item, endMs: Number(event.target.value), confidence: manual }))} /></label></div>}
      {line.words.map((word) => <div key={word.id} className="ml-2 space-y-1"><div className="flex flex-wrap items-center gap-2"><b className="min-w-20">{word.text}</b><TimeField label={`${word.text} word start milliseconds`} value={word.startMs} onChange={(value) => changeWord(section.id, line.id, word.id, (item) => ({ ...item, startMs: value, confidence: manual }))} /><TimeField label={`${word.text} word end milliseconds`} value={word.endMs} onChange={(value) => changeWord(section.id, line.id, word.id, (item) => ({ ...item, endMs: value, confidence: manual }))} /><input className="w-36 rounded border border-white/10 bg-black/20 px-1" aria-label={`${word.text} syllables`} title="Separate syllables with hyphens" defaultValue={syllablesOf(word).map((item) => item.text).join("-")} onBlur={(event) => changeWord(section.id, line.id, word.id, (item) => ({ ...item, syllables: makeSyllables(event.target.value, item.syllables) }))} />{word.confidence && <span>{word.confidence.source} {Math.round(word.confidence.score * 100)}%</span>}</div>{syllablesOf(word).map((syllable) => <div key={syllable.id} className="ml-4 flex flex-wrap items-center gap-2 text-neutral-400"><span className="min-w-20">{syllable.text}</span><TimeField label={`${word.text} ${syllable.text} syllable start milliseconds`} value={syllable.startMs} onChange={(value) => changeSyllable(section.id, line.id, word.id, syllable.id, (item) => ({ ...item, startMs: value, confidence: manual }))} /><TimeField label={`${word.text} ${syllable.text} syllable end milliseconds`} value={syllable.endMs} onChange={(value) => changeSyllable(section.id, line.id, word.id, syllable.id, (item) => ({ ...item, endMs: value, confidence: manual }))} />{syllable.confidence && <span>{Math.round(syllable.confidence.score * 100)}%</span>}</div>)}</div>)}</div>)}<button type="button" onClick={() => changeSection(section.id, (item) => ({ ...item, lines: [...item.lines, makeLine()] }))}>+ Line</button></div>)}
    <button type="button" onClick={() => onChange({ ...document, sections: [...document.sections, makeSection(`Verse ${document.sections.length + 1}`)] })}>+ Section</button>
    <div className="border-t border-white/10 pt-3 space-y-2"><b>Version history</b><div className="flex gap-2"><input className="input" aria-label="Version label" value={versionLabel} onChange={(event) => setVersionLabel(event.target.value)} /><button type="button" onClick={() => { onChange(saveLyricsVersion(document, versionLabel)); setVersionLabel(""); }}>Save version</button></div>{document.versions.map((version) => <div key={version.id} className="flex justify-between"><span>{version.label} Ã‚Â· {new Date(version.createdAt).toLocaleString()}</span><button type="button" onClick={() => onChange(restoreLyricsVersion(document, version.id))}>Restore</button></div>)}</div>
  </div>;
}
